### PR TITLE
Flow scope

### LINKED ISSUE #1218: Wrong Flow.switchMap { }.take() behaviour
Kotlin 1.3.31, kotlinx.coroutines 1.2.1

This code:
```kotlin
runBlocking {
  println(
    flowOf(1, 2, 3, 4, 5)
      .switchMap { x -> flow { emit(x) } }
      .take(1)
      .toList()
  )
}
```
prints wrong result: [1, 2, 3, 4, 5].

It should prints [1].

### PR DESCRIPTION
**Pull request by qwwdfsad**
Fixes #1218 and #1128

### CODE REVIEW

File: kotlinx-coroutines-core/common/test/flow/operators/FlowOnTest.kt [hunk 1]
```diff
@@ -6,6 +6,7 @@ package kotlinx.coroutines.flow
 
 import kotlinx.coroutines.*
 import kotlinx.coroutines.channels.*
+import kotlin.math.*
```
Comment (qwwdfsad) [inline kotlinx-coroutines-core/common/test/flow/operators/FlowOnTest.kt]: unused import

File: kotlinx-coroutines-core/common/src/JobSupport.kt [hunk 2]
```diff
@@ -319,6 +319,31 @@ public open class JobSupport constructor(active: Boolean) : Job, ChildJob, Paren
         cancelParent(cause) // tentative cancellation -- does not matter if there is no parent
     }
 
+    /**
+     * The method that is invoked when the job is cancelled to possible propagate cancellation to the parent.
+     * Returns `true` if the parent is responsible for handling the exception, `false` otherwise.
+     *
+     * Invariant: never returns `true` for instances of [CancellationException], otherwise such exception
```
Comment (elizarov) [inline kotlinx-coroutines-core/common/src/JobSupport.kt]: Wrong doc: Never returns `false` for instance of CancellationException.

File: kotlinx-coroutines-core/common/src/JobSupport.kt [hunk 3]
```diff
@@ -594,17 +619,27 @@ public open class JobSupport constructor(active: Boolean) : Job, ChildJob, Paren
...
     }
 
-    // Child was cancelled with cause
-    // It is overridden in supervisor implementations to ignore child cancellation
-    public open fun childCancelled(cause: Throwable): Boolean =
-        cancelImpl(cause) && handlesException
+    /**
+     * Returns `true` if job should cancel itself on child [CancellationException].
+     */
+    public open fun cancelOnChildCancellation(cause: CancellationException) = false
```
Comment (elizarov) [inline kotlinx-coroutines-core/common/src/JobSupport.kt]: It seems wasteful to have a separate overridable function only for the use by flow scopes. I suggest to have them override `childCancelled` just supervisor jobs do.

File: kotlinx-coroutines-core/common/src/JobSupport.kt [hunk 4]
```diff
@@ -594,17 +619,27 @@ public open class JobSupport constructor(active: Boolean) : Job, ChildJob, Paren
...
+    /**
+     * Child was cancelled with a cause.
+     * In this method parent decides whether it cancels itself (e.g. on a critical failure) and
+     * whether it handles the exception of the child.
+     * It is overridden in supervisor implementations to completely ignore any child cancellation.
+     */
+    public open fun childCancelled(cause: Throwable): Boolean {
+        if (cause is CancellationException && !cancelOnChildCancellation(cause)) return true
+        return cancelImpl(cause) && handlesException
+    }
```
Comment (elizarov) [inline kotlinx-coroutines-core/common/src/JobSupport.kt]: I suggest to replace it with the following code to make "default" cancellation logic clearer and to fix a bug with `produce` coroutine (failure of a child shall immediately cancel the channel because it is doomed to fail and should not wait for main coroutine's failure):
```
    public open fun childCancelled(cause: Throwable): Boolean {
        if (cause is CancellationException) return true
        return cancelInternal(cause)
    }
```

File: kotlinx-coroutines-core/common/src/flow/internal/FlowScope.kt [hunk 5]
```diff
@@ -0,0 +1,58 @@
...
+        }
+    }
+
+internal class FlowScope<T, R>(
+    private val collector: FlowCollector<R>,
+    context: CoroutineContext,
+    uCont: Continuation<T>
+) : ScopeCoroutine<T>(context, uCont), FlowCollector<R> {
+
+    public override fun cancelOnChildCancellation(cause: CancellationException) = cause !is ChildCancelledException
```
Comment (elizarov) [inline kotlinx-coroutines-core/common/src/flow/internal/FlowScope.kt]: It should override `childCancelled` for consistency with supervisor scopes (that override it to return `false`) and to make the logic more "straight" (without double negations). Use the following code in overridden implementation:

```
    override fun childCancelled(cause: Throwable): Boolean {
        if (cause is ChildCancelledException) return true
        return cancelInternal(cause)
    }
```

File: kotlinx-coroutines-core/common/src/flow/internal/FlowScope.kt [hunk 6]
```diff
@@ -0,0 +1,58 @@
...
+ *     launch {
+ *         throw CancellationException()
+ *     }
+ * } // <- CE will be rethrown here
+ * ```
+ *
+ * Basically, it is shorthand for:
+ * ```
+ * flow {
+ *     coroutineScope {
```
Comment (elizarov) [inline kotlinx-coroutines-core/common/src/flow/internal/FlowScope.kt]: I'll need a separate `flowScope` primitive, too, for other operators I'm working on, so it makes sense to have a separate internal `flowScope` primitive too and say here that `scopedFlow { ... }` is a shortcut for `flow { flowScope { ... } }` that sames on lambdas (one lambda instead of two)

File: kotlinx-coroutines-core/common/src/flow/internal/FlowScope.kt [hunk 7]
```diff
@@ -0,0 +1,58 @@
...
+ *         ...
+ *     }
+ * }
+ * ```
+ * with additional constraint on cancellation.
+ * To cancel child without cancelling itself, `cancel(ChildCancelledException())` should be used.
+ */
+internal fun <R> scopedFlow(@BuilderInference block: suspend FlowScope<Unit, R>.() -> Unit): Flow<R> =
```
Comment (elizarov) [inline kotlinx-coroutines-core/common/src/flow/internal/FlowScope.kt]: More correctly it should be called `unsafeScopedFlow`. I would also consider an alternative signature of this function passing collector as value parameter, so that there is no need to go through delegated call on each emit:

```
fun <T> unsafeScopedFlow(@BuilderInference block: suspend CoroutineScope.(FlowCollector<T>) -> Unit): Flow<T> = 
    unsafeFlow { 
        val collector = this
        flowScope { block(collector) }
    }
```

Comment (qwwdfsad) [reply kotlinx-coroutines-core/common/src/flow/internal/FlowScope.kt]: I'd prefer to avoid "unsafe" in operators implementation

File: kotlinx-coroutines-core/common/src/flow/internal/FlowCoroutine.kt [hunk 8]
```diff
@@ -0,0 +1,61 @@
...
+ * For example:
+ * ```
+ * flowScope {
+ *     launch {
+ *         throw CancellationException()
+ *     }
+ * } // <- CE will be rethrown here
+ * ```
+ */
+internal suspend fun <R> flowScope(@BuilderInference block: suspend CoroutineScope.() -> R): R =
```
Comment (qwwdfsad) [inline kotlinx-coroutines-core/common/src/flow/internal/FlowCoroutine.kt]: An interesting question: do we want to guarantee the same behaviour for `channelFlow`?
For example:
```
fun Flow<Int>.bufferWithTimeout(): Flow<Int> = channelFlow {
    launch {
        delay(Long.MAX_VALUE)
    }
    launch {
        collect {
            withTimeout(-1) {
                send(it)
            }
        }
    }
}
```

do we expect this flow to ever complete?

File: kotlinx-coroutines-core/common/src/flow/internal/FlowCoroutine.kt [hunk 9]
```diff
@@ -0,0 +1,82 @@
...
+private class FlowCoroutine<T>(context: CoroutineContext, uCont: Continuation<T>) :
+    ScopeCoroutine<T>(context, uCont) {
+
+    public override fun childCancelled(cause: Throwable): Boolean {
+        if (cause is ChildCancelledException) return true
+        return cancelImpl(cause)
+    }
+}
+
+private class FlowProduceCoroutine<T>(parentContext: CoroutineContext, channel: Channel<T>) :
```
Comment (qwwdfsad) [inline kotlinx-coroutines-core/common/src/flow/internal/FlowCoroutine.kt]: indent
