### PR TITLE
User Class.forName instead of ServiceLoader to instantiate Dispatchers.Main on Android

### LINKED ISSUE #878: Slow android Dispatchers.Main init
It seems Android Main dispatcher initialization / discovery can be quite slow currently.

On a Nokia 8 device my application startup time went from 250ms to 500ms (on release mode). I know that 250ms does not sound much but it's pretty much 2 times slower startup time and it does impact the users as they often want the fastest possible startup time for this kind of application. And I still have to see on older devices if the impact is 250ms or linear with the device power.

See attached flamechart (It's from the debug app with full trace profiling so the times are insanely slow but was necessary to find the issue).

coroutine flame chart

Is there a way to bypass that slow factory discovery and statically create my own Main dispatcher on Android to avoid that slowdown?

### LINKED ISSUE #1557: Crash after upgrade from 1.3.0 to 1.3.1
Since I updated to coroutines 1.3.1 on Android projects it started to crash on all existing 3rd libraries that using coroutines too. 

It is just minor bugfix version I would not expect backward incompatibility on such release.

But there is this small unimportant note:

> Note: Kotlin/Native artifacts are now published with Gradle metadata format version 1.0, so you will need Gradle version 5.3 or later to use this version of kotlinx.coroutines in your Kotlin/Native project.

Can this be a reason?

My project is using Gradle 5.6.2, but the library is using an older version than 5.3

```
    java.lang.IllegalStateException: Module with the Main dispatcher is missing. Add dependency providing the Main dispatcher, e.g. 'kotlinx-coroutines-android'
        at kotlinx.coroutines.internal.MissingMainCoroutineDispatcher.missing(MainDispatchers.kt:90)
        at kotlinx.coroutines.internal.MissingMainCoroutineDispatcher.isDispatchNeeded(MainDispatchers.kt:71)
        at kotlinx.coroutines.DispatchedKt.resumeCancellable(Dispatched.kt:420)
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:26)
        at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:109)
        at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:154)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:54)
        at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
        at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
```

I have both dependencies

```
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.1'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.3.1'

```

### PR DESCRIPTION
**Pull request by qwwdfsad**
`ServiceLoader` has proven itself as a very unstable mechanism on Android (see all the issues in a `loadMainDispatcherFactory` comment). Moreover, failures in SL are considered by `kotlinx.coroutines` users as errors in the library itself, making it look unstable. We are not really happy with that, so here is an attempt to avoid `ServiceLoader` on Android for `Dispatchers.Main`.

Though I am not sure whether this change should be merged in `kotlinx.coroutines`. Moreover, I am not sure how exactly to evaluate the potential impact of this change.
@wojtek-kalicinski and @JakeWharton could you please help with reviewing this change first?

Fixes #1557
Fixes #878

### CODE REVIEW

File: kotlinx-coroutines-core/jvm/src/internal/FastServiceLoader.kt [hunk 1]
```diff
@@ -20,7 +27,59 @@ import java.util.zip.*
...
+     * that may already be injected vis SL, so we are not using the same technique for it.
+     */
+    internal fun loadMainDispatcherFactory(): List<MainDispatcherFactory> {
+        val clz = MainDispatcherFactory::class.java
+        if (!ANDROID_DETECTED) {
+            return load(clz, clz.classLoader)
+        }
+
+        return try {
+            val result = ArrayList<MainDispatcherFactory>()
```
Comment (JakeWharton) [inline kotlinx-coroutines-core/jvm/src/internal/FastServiceLoader.kt]: nit: pre-size to 2

File: kotlinx-coroutines-core/jvm/src/internal/FastServiceLoader.kt [hunk 2]
```diff
@@ -5,6 +5,13 @@ import java.net.*
 import java.util.*
 import java.util.jar.*
 import java.util.zip.*
+import kotlin.collections.ArrayList
+
+/**
+ * TODO investigate possible java.vendor values for fallbacks
+ * Don't use JvmField here to enable R8 optimizations via "assumenosideeffects"
+ */
+internal val ANDROID_DETECTED = systemProp("java.vendor")?.toLowerCase()?.contains("android") ?: false
```
Comment (JakeWharton) [inline kotlinx-coroutines-core/jvm/src/internal/FastServiceLoader.kt]: I've seen this used in the past, but I'm not sure anything actually guarantees that this string is present. Another reliable way to check is to try to load any Android class (e.g., `Class.forName("android.os.Build")` and then set true or false. R8 will eliminate the lookup so it will become a constant value which should then be inlined so the `if` and thus `load` are removed.

File: kotlinx-coroutines-core/jvm/src/internal/FastServiceLoader.kt [hunk 3]
```diff
@@ -20,7 +27,59 @@ import java.util.zip.*
...
+    /*
+     * This method is inline to have a direct Class.forName("string literal") in the byte code to avoid weird interactions with ProGuard/R8.
+     */
+    @Suppress("NOTHING_TO_INLINE")
+    private inline fun createInstanceOf(
+        baseClass: Class<MainDispatcherFactory>,
+        serviceClass: String
+    ): MainDispatcherFactory? {
+        return try {
+            val clz = Class.forName(serviceClass, true, baseClass.classLoader)
```
Comment (JakeWharton) [inline kotlinx-coroutines-core/jvm/src/internal/FastServiceLoader.kt]: We should confirm that calls to `forName` in this three-argument form can be replaced with class constants by R8. I'll do that.

Comment (qwwdfsad) [reply kotlinx-coroutines-core/jvm/src/internal/FastServiceLoader.kt]: Thanks!

**Comment by wojtek-kalicinski** [comment]
In principle it looks good. I'm wondering if you then still want to have the R8-specific `assumenosideeffects class kotlinx.coroutines.internal.MainDispatcherLoader { boolean FAST_SERVICE_LOADER_ENABLED` configs... unless you treat them as fallback in case `Class.forName` fails, though I'm not sure if that would ever happen

File: kotlinx-coroutines-core/jvm/src/internal/FastServiceLoader.kt (hunk 3 above)
Comment (JakeWharton) [reply kotlinx-coroutines-core/jvm/src/internal/FastServiceLoader.kt]: So far found at least one problem: https://issuetracker.google.com/issues/141678220

The use of the three-arg variant of this method also means that R8 cannot (currently) rewrite this into a `const-class` bytecode at compile time. This is probably okay, since this code only runs once. And it's something that can be investigated in the future. I actually hope to get code like this eventually rewritten as a direct call to the constructor!
