### PR TITLE
SharedFlow: Fix scenario with concurrent emitters and cancellation of subscriber

### LINKED ISSUE #2356: SharedFlow ClassCastException cannot be cast to SharedFlowImpl$Emitter
Tried migrating from BroadcastChannels to SharedFlow, but suffering this ClassCastException. I did not manage to create small reproducible example. Let me know how I can help you investigate further.
 
My emitter:
```kotlin
private val _recordAddedFlow: MutableSharedFlow<RecordAdded> = MutableSharedFlow(1)
val recordAddedFlow: SharedFlow<RecordAdded> = _recordAddedFlow.asSharedFlow()

GlobalScope.launch {
    ...
    _recordAddedFlow.emit(RecordAdded(...))
    ....
}
```

Collector side:
```kotlin
recordAddedFlow
            .dropWhile {
                ...
            }
            .take(1)
            .collectWithTimeout("error message", timeoutInMilliseconds)
```
```kotlin
suspend fun <T> Flow<T>.collectWithTimeout(message: String, timeoutInMilliseconds: Long) {
    try {
        withTimeout(timeout) {
            collect()
        }
    } catch (e: TimeoutCancellationException) {
        throw RuntimeException("Timeout of ${timeoutInMilliseconds / 1000}s elapsed. $message")
    }
}
```

Stack trace:
```kotlin
java.lang.ClassCastException: com.....PublishListener$RecordAdded cannot be cast to kotlinx.coroutines.flow.SharedFlowImpl$Emitter
	at kotlinx.coroutines.flow.SharedFlowImpl.updateCollectorIndexLocked$kotlinx_coroutines_core(SharedFlow.kt:490)
	at kotlinx.coroutines.flow.SharedFlowSlot.freeLocked(SharedFlow.kt:238)
	at kotlinx.coroutines.flow.SharedFlowSlot.freeLocked(SharedFlow.kt:220)
	at kotlinx.coroutines.flow.internal.AbstractSharedFlow.freeSlot(AbstractSharedFlow.kt:83)
	at kotlinx.coroutines.flow.SharedFlowImpl.collect(SharedFlow.kt:318)
	at kotlinx.coroutines.flow.ReadonlySharedFlow.collect(Share.kt)
	at kotlinx.coroutines.flow.FlowKt__LimitKt$dropWhile$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:115)
	at kotlinx.coroutines.flow.FlowKt__LimitKt$take$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:116)
	at kotlinx.coroutines.flow.FlowKt__CollectKt.collect(Collect.kt:30)
	at kotlinx.coroutines.flow.FlowKt.collect(Unknown Source)
	at com.....FlowExtensionsKt$collectWithTimeout$2.invokeSuspend(FlowExtensions.kt:13)
	at com.....FlowExtensionsKt$collectWithTimeout$2.invoke(FlowExtensions.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:102)
	at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:148)
	at kotlinx.coroutines.TimeoutKt.withTimeout(Timeout.kt:44)
	at com.....FlowExtensionsKt.collectWithTimeout(FlowExtensions.kt:12)
	at com....Xyz.waitForRecordToBePublished(Xyz.kt:413)
```

Screenshot 2020-11-01 at 23 12 05

### PR DESCRIPTION
**Pull request by elizarov**
* Added a specific test for a problematic scenario.
* Added stress test with concurrent emitters and subscribers that come and go.

Fixes #2356

### CODE REVIEW

File: kotlinx-coroutines-core/jvm/test/flow/SharedFlowStressTest.kt [hunk 1]
```diff
@@ -0,0 +1,77 @@
...
+            assertNotEquals(lastConsumed, consumed)
+            lastProduced = produced
+            lastConsumed = consumed
+        }
+        jobs.forEach { it.cancel() }
+        jobs.forEach { it.join() }
+        println("total: produced = ${totalProduced.value}; consumed = ${totalConsumed.value}")
+    }
+
+    private fun showStats(s: String) {
```
Comment (qwwdfsad) [inline kotlinx-coroutines-core/jvm/test/flow/SharedFlowStressTest.kt:75]: leftover?

**Review by qwwdfsad — APPROVED** [review]

File: kotlinx-coroutines-core/jvm/test/flow/SharedFlowStressTest.kt (hunk 1 above)
Comment (elizarov) [reply kotlinx-coroutines-core/jvm/test/flow/SharedFlowStressTest.kt:75]: Yes. Thanks.
