### PR TITLE
Properly round `Duration` instances to milliseconds

### LINKED ISSUE #3920: `delay(Duration)` improperly coerces nanoseconds and microseconds
**Describe the bug**

I am currently unsure if this is desired behavior, so if it is, please let me know.

When invoking a delay with a `Duration`, the value of that duration is coerced to milliseconds and then delegated to `delay(Long)`. It is not documented behavior that delaying with a duration loses granularity for nanoseconds or microseconds. For example, delaying with `998.75909ms` gets coerced to a call of `998ms` when delegating to `delay(Long)`. 

The offending code is the following: 

```kt
internal fun Duration.toDelayMillis(): Long =
    if (this > Duration.ZERO) inWholeMilliseconds.coerceAtLeast(1) else 0
```

**What happened? What should have happened instead?**

The symptom of this issue is that when working on implementing a cron-like API for delay based job scheduling, I was having jobs invoked up to 600us before they should have been invoked. The end result was that jobs scheduled to occur at the beginning of a second in a certain time zone would invoke early once and then as expected afterwards in quick succession. 

The above function `Duration.toDelaymillis` should likely coerce durations which have a nanosecond component up `duration.inWholeMilliseconds + 1`. 

Locally this implementation is working well for me. 

```kt
internal fun Duration.myToMillis(): Long = if (this > Duration.ZERO) {
    val millis = inWholeMilliseconds
    if (millis * 1_000_000 < inWholeNanoseconds) millis + 1 else millis
} else 0
```

**Provide a Reproducer**

```kt
    @Test fun foo() = runTest(timeout = 1.days) {
        withContext(Dispatchers.Default) {
            while (true) {
                val expectedDuration = 998.milliseconds + 902752.nanoseconds
                val actualDuration = measureTime { delay(expectedDuration) }
                val difference = actualDuration - expectedDuration
                assertTrue(difference.isPositive()) // fails
            }
        }
    }

```

### PR DESCRIPTION
**Pull request by kevincianfarini**
Prior to this commit Durations used for delays or timeouts lost their nanosecond granularity when being converted to a millisecond Long value. This effectively meant that delays could resume prior to when they were scheduled to do so.

This commit solves this by rounding a Duration with nanosecond components up to the next largest millisecond.

Closes #3920

### CODE REVIEW

File: kotlinx-coroutines-core/common/src/Delay.kt [hunk 1]
```diff
@@ -154,8 +154,15 @@ public suspend fun delay(duration: Duration): Unit = delay(duration.toDelayMilli
...
- * Convert this duration to its millisecond value.
- * Positive durations are coerced at least `1`.
+ * Convert this duration to its millisecond value. Durations which have a nanosecond component less than
+ * a single millisecond will be rounded up to the next largest millisecond.
  */
-internal fun Duration.toDelayMillis(): Long =
-    if (this > Duration.ZERO) inWholeMilliseconds.coerceAtLeast(1) else 0
+internal fun Duration.toDelayMillis(): Long {
+    val millis = inWholeMilliseconds
+    val nanosecondsInMillisecond = 1_000_000
```
Comment (kevincianfarini) [inline kotlinx-coroutines-core/common/src/Delay.kt:162]: Is there a better constant I can use for this rather than a random magic number?

File: kotlinx-coroutines-core/common/src/Delay.kt [hunk 2]
```diff
@@ -133,7 +133,7 @@ public suspend fun delay(timeMillis: Long) {
 }
 
 /**
- * Delays coroutine for a given [duration] without blocking a thread and resumes it after the specified time.
+ * Delays coroutine for at least the given [duration] without blocking a thread and resumes it after the specified time.
```
Comment (kevincianfarini) [inline kotlinx-coroutines-core/common/src/Delay.kt:136]: I felt that this was an important distinction which felt natural to make here. Please let me know if I should revert.

File: kotlinx-coroutines-core/common/src/Delay.kt [hunk 3]
```diff
@@ -154,8 +154,15 @@ public suspend fun delay(duration: Duration): Unit = delay(duration.toDelayMilli
...
 
 /**
- * Convert this duration to its millisecond value.
- * Positive durations are coerced at least `1`.
+ * Convert this duration to its millisecond value. Durations which have a nanosecond component less than
+ * a single millisecond will be rounded up to the next largest millisecond.
  */
-internal fun Duration.toDelayMillis(): Long =
-    if (this > Duration.ZERO) inWholeMilliseconds.coerceAtLeast(1) else 0
+internal fun Duration.toDelayMillis(): Long {
```
Comment (denis-bezrukov) [inline kotlinx-coroutines-core/common/src/Delay.kt:160]: it will fail on attempt to do `Duration.INFINITE.toDelayMillis()` as the `Duration.INFINITE.inWholeMilliseconds` returns Long.MAX_VALUE. Adding 1 to it will overflow and return Long.MIN_VALUE. Another place when it may overflow is `millis * nanosecondsInMillisecond` (for any millis duration above Long.MAX_VALUE / 1000_000). 

Probably the easiest way to round it up is to defer all the math to kotlin.time
```
(this + 999999.nanoseconds).inWholeMilliseconds
```

File: kotlinx-coroutines-core/common/src/Delay.kt [hunk 4]
```diff
@@ -154,8 +154,15 @@ public suspend fun delay(duration: Duration): Unit = delay(duration.toDelayMilli
...
+    val millis = inWholeMilliseconds
+    val nanosecondsInMillisecond = 1_000_000
+    return when {
+        this <= Duration.ZERO -> 0L
+        millis * nanosecondsInMillisecond < inWholeNanoseconds -> millis + 1
```
Comment (JakeWharton) [inline kotlinx-coroutines-core/common/src/Delay.kt:165]: It might be more efficient to check `isFinite() && this != millis.milliseconds` since it doesn't involve any math operations (especially on JS where they're slow). Plus I suspect you're not handling overflow with the current code correctly.

**Review by dkhalanskyjb — CHANGES_REQUESTED** [review]

File: kotlinx-coroutines-core/common/src/Delay.kt (hunk 4 above)
Comment (kevincianfarini) [reply kotlinx-coroutines-core/common/src/Delay.kt:165]: Perhaps it's best to do modulo arithmetic?

File: kotlinx-coroutines-core/common/src/Delay.kt (hunk 3 above)
Comment (kevincianfarini) [reply kotlinx-coroutines-core/common/src/Delay.kt:160]: Switched to use modulo arithmetic.

Comment (denis-bezrukov) [reply kotlinx-coroutines-core/common/src/Delay.kt:160]: It will now fail for any large (but finite) number, just because of the precision error when attempting to access `inWholeNanoseconds`

i.e. this one should fail
```
@Test fun large_but_finite() {
    val milliseconds = Long.MAX_VALUE / 10
    assertEquals(
        expected = milliseconds, 
        actual = milliseconds.milliseconds.toDelayMillis(),
    )
}
```
because 
```
Long.MAX_VALUE                | 9223372036854775807
Long.MAX_VALUE/10             | 922337203685477580
In nanos (absolute precision) | 922337203685477580000000 | mod1000000=0
In nanos (coerced to 64bits)  | 9223372036854775807      | mod1000000=775807

```

Comment (kevincianfarini) [reply kotlinx-coroutines-core/common/src/Delay.kt:160]: I see. Good catch. Will delegate to kotlin.time arithmetic.

Comment (kevincianfarini) [reply kotlinx-coroutines-core/common/src/Delay.kt:161]: Updated.

File: kotlinx-coroutines-core/common/src/Delay.kt [hunk 5]
```diff
@@ -154,8 +155,18 @@ public suspend fun delay(duration: Duration): Unit = delay(duration.toDelayMilli
...
+ * Convert this duration to its millisecond value. Durations which have a nanosecond component less than
+ * a single millisecond will be rounded up to the next largest millisecond.
  */
-internal fun Duration.toDelayMillis(): Long =
-    if (this > Duration.ZERO) inWholeMilliseconds.coerceAtLeast(1) else 0
+internal fun Duration.toDelayMillis(): Long {
+    val millis = inWholeMilliseconds
+    return when {
+        !isPositive() -> 0L
+
```
Comment (dkhalanskyjb) [inline kotlinx-coroutines-core/common/src/Delay.kt:165]: Style: in this library, we avoid empty lines inside functions.

File: kotlinx-coroutines-core/common/src/Delay.kt (hunk 3 above)
Comment (dkhalanskyjb) [reply kotlinx-coroutines-core/common/src/Delay.kt:161]: I agree with @denis-bezrukov:
> `(this + 999999.nanoseconds).inWholeMilliseconds`

seems to be the cleanest and, I suspect, also the most efficient solution available to us without getting access to the internals of `Duration`. Here, in realistic cases, it's just a single addition and a conversion to milliseconds.

**Review by dkhalanskyjb — CHANGES_REQUESTED** [review]

File: kotlinx-coroutines-core/common/src/Delay.kt (hunk 3 above)
Comment (kevincianfarini) [reply kotlinx-coroutines-core/common/src/Delay.kt]: Pushed. Thank you two for the review.

File: kotlinx-coroutines-core/common/test/DurationToMillisTest.kt [hunk 6]
```diff
@@ -0,0 +1,71 @@
...
+
+    @Test fun nanosecond_off_by_one_infinity_does_not_overflow() = assertEquals(
+        expected = Long.MAX_VALUE / 1_000_000,
+        actual = (Long.MAX_VALUE - 1L).nanoseconds.toDelayMillis(),
+    )
+
+    @Test fun millisecond_off_by_one_infinity_does_not_overflow() = assertEquals(
+        expected = Long.MAX_VALUE, // INFINITY duration.
+        actual = (Long.MAX_VALUE - 1L).milliseconds.toDelayMillis(),
+    )
```
Comment (kevincianfarini) [inline kotlinx-coroutines-core/common/test/DurationToMillisTest.kt:62]: I actually don't think this is correct now that I look at it again. This duration has no nanosecond sub component and therefore shouldn't be rounded.

File: kotlinx-coroutines-core/common/test/DurationToMillisTest.kt [hunk 7]
```diff
@@ -0,0 +1,71 @@
...
+import kotlin.time.Duration.Companion.milliseconds
+import kotlin.time.Duration.Companion.nanoseconds
+import kotlin.time.Duration.Companion.seconds
+
+class DurationToMillisTest {
+
+    @Test fun negative_duration_coerced_to_zero_millis() = assertEquals(
+        expected = 0L,
+        actual = (-1).seconds.toDelayMillis(),
+    )
```
Comment (dkhalanskyjb) [inline kotlinx-coroutines-core/common/test/DurationToMillisTest.kt:17]: Style: please look at how all the other tests are structured in this library.
* Test names: we use camel case, and also, all test names begin with `test`.
* Indentation is different: `@Test` should be on a separate line, function calls are typically on a single line, etc.
* Explicit parameter names here don't add much and are mostly noise.

**Comment by kevincianfarini** [comment]
Hi! If there's any other desired changes I'm happy to make them.

**Comment by dkhalanskyjb** [comment]
Please rebase your changes on top of `develop` and set that as the base of the PR. See https://github.com/Kotlin/kotlinx.coroutines/blob/master/CONTRIBUTING.md#submitting-prs

**Comment by kevincianfarini** [comment]
Done. Sorry, I should have checked the contribution guide first.

**Comment by kevincianfarini** [comment]
Do we think there's a chance this will be merged prior to the next version release? 😄

**Comment by dkhalanskyjb** [comment]
Yes.

**Review by dkhalanskyjb — APPROVED** [review]
:thumb-up:

**Comment by kevincianfarini** [comment]
Nice! Thank you.
