### PR TITLE
Adjust behavior of conflated channel to deliver last value

### LINKED ISSUE #332: ConflatedChannel unexpected behavior
```kotlin
val conflatedChannel = ConflatedChannel<Int>()
conflatedChannel.offer(1)
conflatedChannel.offer(2)
conflatedChannel.close()

conflatedChannel.receive() // expected receive 2 but error "Channel was closed"
```
It's very confusing, because `close()` method:
> Conceptually, its sends a special "close token" over this channel.

Is the `"close token"` treated equality with an element of Channel? I think it shouldn't be, then it shouldn't replace latest element of ConflatedChannel.

### LINKED ISSUE #1235: Adjust behavior of conflated channel to match use-case of intermediate values
See long discussion in #332. Here is TL;DR. Current behavior of `Channel(CONFLATED)` (`ConflatedChannel`) can be demonstrated with the following code ([play](https://pl.kotl.in/lM29toYHW)):

```
fun main() = runBlocking {
    val channel = produce(capacity = Channel.CONFLATED) { 
        send(1); send(2); send(3); send(4)
    }
    channel.consumeEach { println(it) } // prints only 1
}
```

What happens here is that closing a channel is considered to send a "value" that overwrites last sent value. This is subtle behavior and it is not clearly spelled out in docs. In fact, on can argue that docs imply a different behavior. Anyway, this is not what one wants when conflated channel is used to send intermediate values of some computation. In this case one needs to ensure that the most recent value is always delivered. This use-cases seems to be most prominent one and this proposal is to change behavior of conflated channels to match it, so that the above code prints 1 and 4.

### PR DESCRIPTION
**Pull request by elizarov**
Fixes #1235
Fixes #332

### CODE REVIEW

File: kotlinx-coroutines-core/common/src/channels/ConflatedChannel.kt [hunk 1]
```diff
@@ -24,31 +24,20 @@ internal open class ConflatedChannel<E> : AbstractChannel<E>() {
     protected final override val isBufferAlwaysFull: Boolean get() = false
     protected final override val isBufferFull: Boolean get() = false
 
-    override fun onClosedIdempotent(closed: LockFreeLinkedListNode) {
```
Comment (qwwdfsad) [inline kotlinx-coroutines-core/common/src/channels/ConflatedChannel.kt]: This change makes the channel non-linearizable (see `ChannelLinearizabilityTest.testConflatedChannelLinearizability`).

`onClosedIdempotent ` call should conflate all sent elements except the last one.
Otherwise, weird non-linearizable executions are possible when closing thread interacts with the channel after `close`.

**Comment by qwwdfsad** [comment]
I think we should document this behaviour somewhere, e.g. around `Factory.CONFLATED`

File: kotlinx-coroutines-core/common/src/channels/ConflatedChannel.kt [hunk 2]
```diff
@@ -24,31 +24,20 @@ internal open class ConflatedChannel<E> : AbstractChannel<E>() {
...
-        conflatePreviousSendBuffered(closed)
-    }
```
[the remark this answers is not in the document]
Comment (elizarov) [reply kotlinx-coroutines-core/common/src/channels/ConflatedChannel.kt]: Good catch!

File: kotlinx-coroutines-core/common/src/channels/ConflatedChannel.kt (hunk 1 above)
Comment (elizarov) [reply kotlinx-coroutines-core/common/src/channels/ConflatedChannel.kt]: Yes hell, indeed.

**Comment by elizarov** [comment]
I've fixed the linearizability & moved the code. As for docs, it seems to be _already_ documented this way right here: https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.channels/-channel/index.html
