### PR TITLE
Move UI dispatcher to common Dispatchers.Main

### LINKED ISSUE #626: Dispatchers.Main causes IDE error loops in 0.27.0
This issue doesn't happen on version 0.26.1, and neither invalidate caches and restart nor refresh dependencies solve it on 0.27.0

When I hover the mouse with command held down, it recognizes everything but `.Main` that comes after `Dispatchers`, even when imported manually (autocomplete doesn't work for it).

I'm forced to revert to 0.26.1 to work on an update for [BleGattCoroutines](https://github.com/Beepiz/BleGattCoroutines) because of this.

Title of the IDE error: `Worker exited due to exception`

File `/Users/MysUserName/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx-coroutines-android/0.27.0/d39131c2f7b764a793152c5fa61205033d5553a0/kotlinx-coroutines-android-0.27.0.jar!/kotlinx/coroutines/experimental/android/HandlerDispatcherKt.class_file.txt`:

<details>

```log
// IntelliJ API Decompiler stub source generated from a class file
// Implementation of methods is not available

package kotlinx.coroutines.experimental.android

private const val MAX_DELAY: kotlin.Long /* compiled code */

@field:kotlin.jvm.JvmField internal val Main: kotlinx.coroutines.experimental.android.HandlerDispatcher /* compiled code */

private var choreographer: android.view.Choreographer? /* compiled code */

internal val mainHandler: android.os.Handler /* compiled code */

public val kotlinx.coroutines.experimental.Dispatchers.Main: kotlinx.coroutines.experimental.android.HandlerDispatcher /* compiled code */

public suspend fun awaitFrame(): kotlin.Long { /* compiled code */ }

private fun postFrameCallback(choreographer: android.view.Choreographer, cont: kotlinx.coroutines.experimental.CancellableContinuation<kotlin.Long>): kotlin.Unit { /* compiled code */ }

private fun updateChoreographerAndPostFrameCallback(cont: kotlinx.coroutines.experimental.CancellableContinuation<kotlin.Long>): kotlin.Unit { /* compiled code */ }

@kotlin.jvm.JvmName @kotlin.jvm.JvmOverloads public fun android.os.Handler.asCoroutineDispatcher(name: kotlin.String? /* = compiled code */): kotlinx.coroutines.experimental.android.HandlerDispatcher { /* compiled code */ }

@android.support.annotation.VisibleForTesting internal fun android.os.Looper.asHandler(async: kotlin.Boolean): android.os.Handler { /* compiled code */ }

```

</details>

File `stubTree.txt`:

<details>
```log
PsiJetFileStubImpl[package=kotlinx.coroutines.experimental.android]
  KotlinStub$PACKAGE_DIRECTIVE
    KotlinStub$DOT_QUALIFIED_EXPRESSION
      KotlinStub$DOT_QUALIFIED_EXPRESSION
        KotlinStub$DOT_QUALIFIED_EXPRESSION
          KotlinStub$REFERENCE_EXPRESSION[referencedName=kotlinx]
          KotlinStub$REFERENCE_EXPRESSION[referencedName=coroutines]
        KotlinStub$REFERENCE_EXPRESSION[referencedName=experimental]
      KotlinStub$REFERENCE_EXPRESSION[referencedName=android]
  KotlinStub$IMPORT_LIST
  KotlinStub$PROPERTY[fqName=kotlinx.coroutines.experimental.android.MAX_DELAY, hasDelegate=false, hasDelegateExpression=false, hasInitializer=false, hasReturnTypeRef=true, isExtension=false, isTopLevel=true, isVar=false, name=MAX_DELAY]
    KotlinStub$MODIFIER_LIST[private const]
    KotlinStub$TYPE_REFERENCE
      KotlinStub$USER_TYPE
        KotlinStub$USER_TYPE
          KotlinStub$REFERENCE_EXPRESSION[referencedName=kotlin]
        KotlinStub$REFERENCE_EXPRESSION[referencedName=Long]
  KotlinStub$PROPERTY[fqName=kotlinx.coroutines.experimental.android.Main, hasDelegate=false, hasDelegateExpression=false, hasInitializer=false, hasReturnTypeRef=true, isExtension=false, isTopLevel=true, isVar=false, name=Main]
    KotlinStub$MODIFIER_LIST[internal]
      KotlinStub$ANNOTATION_ENTRY[hasValueArguments=false, shortName=JvmField]
        KotlinStub$ANNOTATION_TARGET[useSiteTarget=FIELD]
        KotlinStub$CONSTRUCTOR_CALLEE
          KotlinStub$TYPE_REFERENCE
            KotlinStub$USER_TYPE
              KotlinStub$USER_TYPE
                KotlinStub$USER_TYPE
                  KotlinStub$REFERENCE_EXPRESSION[referencedName=kotlin]
                KotlinStub$REFERENCE_EXPRESSION[referencedName=jvm]
              KotlinStub$REFERENCE_EXPRESSION[referencedName=JvmField]
    KotlinStub$TYPE_REFERENCE
      KotlinStub$USER_TYPE
        KotlinStub$USER_TYPE
          KotlinStub$USER_TYPE
            KotlinStub$USER_TYPE
              KotlinStub$USER_TYPE
                KotlinStub$REFERENCE_EXPRESSION[referencedName=kotlinx]
              KotlinStub$REFERENCE_EXPRESSION[referencedName=coroutines]
            KotlinStub$REFERENCE_EXPRESSION[referencedName=experimental]
          KotlinStub$REFERENCE_EXPRESSION[referencedName=android]
        KotlinStub$REFERENCE_EXPRESSION[referencedName=HandlerDispatcher]
  KotlinStub$PROPERTY[fqName=kotlinx.coroutines.experimental.android.choreographer, hasDelegate=false, hasDelegateExpression=false, hasInitializer=false, hasReturnTypeRef=true, isExtension=false, isTopLevel=true, isVar=true, name=choreographer]
    KotlinStub$MODIFIER_LIST[private]
    KotlinStub$TYPE_REFERENCE
      KotlinStub$NULLABLE_TYPE
        KotlinStub$USER_TYPE
          KotlinStub$USER_TYPE
            KotlinStub$USER_TYPE
              KotlinStub$REFERENCE_EXPRESSION[referencedName=android]
            KotlinStub$REFERENCE_EXPRESSION[referencedName=view]
          KotlinStub$REFERENCE_EXPRESSION[referencedName=Choreographer]
  KotlinStub$PROPERTY[fqName=kotlinx.coroutines.experimental.android.mainHandler, hasDelegate=false, hasDelegateExpression=false, hasInitializer=false, hasReturnTypeRef=true, isExtension=false, isTopLevel=true, isVar=false, name=mainHandler]
    KotlinStub$MODIFIER_LIST[internal]
    KotlinStub$TYPE_REFERENCE
      KotlinStub$USER_TYPE
        KotlinStub$USER_TYPE
          KotlinStub$USER_TYPE
            KotlinStub$REFERENCE_EXPRESSION[referencedName=android]
          KotlinStub$REFERENCE_EXPRESSION[referencedName=os]
        KotlinStub$REFERENCE_EXPRESSION[referencedName=Handler]
  KotlinStub$PROPERTY[fqName=kotlinx.coroutines.experimental.android.Main, hasDelegate=false, hasDelegateExpression=false, hasInitializer=false, hasReturnTypeRef=true, isExtension=true, isTopLevel=true, isVar=false, name=Main]
    KotlinStub$MODIFIER_LIST[public]
      KotlinStub$ANNOTATION_ENTRY[hasValueArguments=false, shortName=JvmField]
        KotlinStub$ANNOTATION_TARGET[useSiteTarget=FIELD]
        KotlinStub$CONSTRUCTOR_CALLEE
          KotlinStub$TYPE_REFERENCE
            KotlinStub$USER_TYPE
              KotlinStub$USER_TYPE
                KotlinStub$USER_TYPE
                  KotlinStub$REFERENCE_EXPRESSION[referencedName=kotlin]
                KotlinStub$REFERENCE_EXPRESSION[referencedName=jvm]
              KotlinStub$REFERENCE_EXPRESSION[referencedName=JvmField]
    KotlinStub$TYPE_REFERENCE
      KotlinStub$USER_TYPE
        KotlinStub$USER_TYPE
          KotlinStub$USER_TYPE
            KotlinStub$USER_TYPE
              KotlinStub$REFERENCE_EXPRESSION[referencedName=kotlinx]
            KotlinStub$REFERENCE_EXPRESSION[referencedName=coroutines]
          KotlinStub$REFERENCE_EXPRESSION[referencedName=experimental]
        KotlinStub$REFERENCE_EXPRESSION[referencedName=Dispatchers]
    KotlinStub$TYPE_REFERENCE
      KotlinStub$USER_TYPE
        KotlinStub$USER_TYPE
          KotlinStub$USER_TYPE
            KotlinStub$USER_TYPE
              KotlinStub$USER_TYPE
                KotlinStub$REFERENCE_EXPRESSION[referencedName=kotlinx]
              KotlinStub$REFERENCE_EXPRESSION[referencedName=coroutines]
            KotlinStub$REFERENCE_EXPRESSION[referencedName=experimental]
          KotlinStub$REFERENCE_EXPRESSION[referencedName=android]
        KotlinStub$REFERENCE_EXPRESSION[referencedName=HandlerDispatcher]
  KotlinStub$FUN[fqName=kotlinx.coroutines.experimental.android.awaitFrame, hasBlockBody=true, hasBody=true, hasTypeParameterListBeforeFunctionName=false, isExtension=false, isTopLevel=true, mayHaveContract=false, name=awaitFrame]
    KotlinStub$MODIFIER_LIST[public suspend]
    KotlinStub$VALUE_PARAMETER_LIST
    KotlinStub$TYPE_REFERENCE
      KotlinStub$USER_TYPE
        KotlinStub$USER_TYPE
          KotlinStub$REFERENCE_EXPRESSION[referencedName=kotlin]
        KotlinStub$REFERENCE_EXPRESSION[referencedName=Long]
  KotlinStub$FUN[fqName=kotlinx.coroutines.experimental.android.postFrameCallback, hasBlockBody=true, hasBody=true, hasTypeParameterListBeforeFunctionName=false, isExtension=false, isTopLevel=true, mayHaveContract=false, name=postFrameCallback]
    KotlinStub$MODIFIER_LIST[private]
    KotlinStub$VALUE_PARAMETER_LIST
      KotlinStub$VALUE_PARAMETER[fqName=null, hasDefaultValue=false, hasValOrVar=false, isMutable=false, name=choreographer]
        KotlinStub$TYPE_REFERENCE
          KotlinStub$USER_TYPE
            KotlinStub$USER_TYPE
              KotlinStub$USER_TYPE
                KotlinStub$REFERENCE_EXPRESSION[referencedName=android]
              KotlinStub$REFERENCE_EXPRESSION[referencedName=view]
            KotlinStub$REFERENCE_EXPRESSION[referencedName=Choreographer]
      KotlinStub$VALUE_PARAMETER[fqName=null, hasDefaultValue=false, hasValOrVar=false, isMutable=false, name=cont]
        KotlinStub$TYPE_REFERENCE
          KotlinStub$USER_TYPE
            KotlinStub$USER_TYPE
              KotlinStub$USER_TYPE
                KotlinStub$USER_TYPE
                  KotlinStub$REFERENCE_EXPRESSION[referencedName=kotlinx]
                KotlinStub$REFERENCE_EXPRESSION[referencedName=coroutines]
              KotlinStub$REFERENCE_EXPRESSION[referencedName=experimental]
            KotlinStub$REFERENCE_EXPRESSION[referencedName=CancellableContinuation]
            KotlinStub$TYPE_ARGUMENT_LIST
              KotlinStub$TYPE_PROJECTION[projectionKind=NONE]
                KotlinStub$TYPE_REFERENCE
                  KotlinStub$USER_TYPE
                    KotlinStub$USER_TYPE
                      KotlinStub$REFERENCE_EXPRESSION[referencedName=kotlin]
                    KotlinStub$REFERENCE_EXPRESSION[referencedName=Long]
    KotlinStub$TYPE_REFERENCE
      KotlinStub$USER_TYPE
        KotlinStub$USER_TYPE
          KotlinStub$REFERENCE_EXPRESSION[referencedName=kotlin]
        KotlinStub$REFERENCE_EXPRESSION[referencedName=Unit]
  KotlinStub$FUN[fqName=kotlinx.coroutines.experimental.android.updateChoreographerAndPostFrameCallback, hasBlockBody=true, hasBody=true, hasTypeParameterListBeforeFunctionName=false, isExtension=false, isTopLevel=true, mayHaveContract=false, name=updateChoreographerAndPostFrameCallback]
    KotlinStub$MODIFIER_LIST[private]
    KotlinStub$VALUE_PARAMETER_LIST
      KotlinStub$VALUE_PARAMETER[fqName=null, hasDefaultValue=false, hasValOrVar=false, isMutable=false, name=cont]
        KotlinStub$TYPE_REFERENCE
          KotlinStub$USER_TYPE
            KotlinStub$USER_TYPE
              KotlinStub$USER_TYPE
                KotlinStub$USER_TYPE
                  KotlinStub$REFERENCE_EXPRESSION[referencedName=kotlinx]
                KotlinStub$REFERENCE_EXPRESSION[referencedName=coroutines]
              KotlinStub$REFERENCE_EXPRESSION[referencedName=experimental]
            KotlinStub$REFERENCE_EXPRESSION[referencedName=CancellableContinuation]
            KotlinStub$TYPE_ARGUMENT_LIST
              KotlinStub$TYPE_PROJECTION[projectionKind=NONE]
                KotlinStub$TYPE_REFERENCE
                  KotlinStub$USER_TYPE
                    KotlinStub$USER_TYPE
                      KotlinStub$REFERENCE_EXPRESSION[referencedName=kotlin]
                    KotlinStub$REFERENCE_EXPRESSION[referencedName=Long]
    KotlinStub$TYPE_REFERENCE
      KotlinStub$USER_TYPE
        KotlinStub$USER_TYPE
          KotlinStub$REFERENCE_EXPRESSION[referencedName=kotlin]
        KotlinStub$REFERENCE_EXPRESSION[referencedName=Unit]
  KotlinStub$FUN[fqName=kotlinx.coroutines.experimental.android.asCoroutineDispatcher, hasBlockBody=true, hasBody=true, hasTypeParameterListBeforeFunctionName=false, isExtension=true, isTopLevel=true, mayHaveContract=false, name=asCoroutineDispatcher]
    KotlinStub$MODIFIER_LIST[public]
      KotlinStub$ANNOTATION_ENTRY[hasValueArguments=false, shortName=JvmName]
        KotlinStub$CONSTRUCTOR_CALLEE
          KotlinStub$TYPE_REFERENCE
            KotlinStub$USER_TYPE
              KotlinStub$USER_TYPE
                KotlinStub$USER_TYPE
                  KotlinStub$REFERENCE_EXPRESSION[referencedName=kotlin]
                KotlinStub$REFERENCE_EXPRESSION[referencedName=jvm]
              KotlinStub$REFERENCE_EXPRESSION[referencedName=JvmName]
      KotlinStub$ANNOTATION_ENTRY[hasValueArguments=false, shortName=JvmOverloads]
        KotlinStub$CONSTRUCTOR_CALLEE
          KotlinStub$TYPE_REFERENCE
            KotlinStub$USER_TYPE
              KotlinStub$USER_TYPE
                KotlinStub$USER_TYPE
                  KotlinStub$REFERENCE_EXPRESSION[referencedName=kotlin]
                KotlinStub$REFERENCE_EXPRESSION[referencedName=jvm]
              KotlinStub$REFERENCE_EXPRESSION[referencedName=JvmOverloads]
    KotlinStub$TYPE_REFERENCE
      KotlinStub$USER_TYPE
        KotlinStub$USER_TYPE
          KotlinStub$USER_TYPE
            KotlinStub$REFERENCE_EXPRESSION[referencedName=android]
          KotlinStub$REFERENCE_EXPRESSION[referencedName=os]
        KotlinStub$REFERENCE_EXPRESSION[referencedName=Handler]
    KotlinStub$VALUE_PARAMETER_LIST
      KotlinStub$VALUE_PARAMETER[fqName=null, hasDefaultValue=false, hasValOrVar=false, isMutable=false, name=name]
        KotlinStub$TYPE_REFERENCE
          KotlinStub$NULLABLE_TYPE
            KotlinStub$USER_TYPE
              KotlinStub$USER_TYPE
                KotlinStub$REFERENCE_EXPRESSION[referencedName=kotlin]
              KotlinStub$REFERENCE_EXPRESSION[referencedName=String]
    KotlinStub$TYPE_REFERENCE
      KotlinStub$USER_TYPE
        KotlinStub$USER_TYPE
          KotlinStub$USER_TYPE
            KotlinStub$USER_TYPE
              KotlinStub$USER_TYPE
                KotlinStub$REFERENCE_EXPRESSION[referencedName=kotlinx]
              KotlinStub$REFERENCE_EXPRESSION[referencedName=coroutines]
            KotlinStub$REFERENCE_EXPRESSION[referencedName=experimental]
          KotlinStub$REFERENCE_EXPRESSION[referencedName=android]
        KotlinStub$REFERENCE_EXPRESSION[referencedName=HandlerDispatcher]
  KotlinStub$FUN[fqName=kotlinx.coroutines.experimental.android.asHandler, hasBlockBody=true, hasBody=true, hasTypeParameterListBeforeFunctionName=false, isExtension=true, isTopLevel=true, mayHaveContract=false, name=asHandler]
    KotlinStub$MODIFIER_LIST[internal]
      KotlinStub$ANNOTATION_ENTRY[hasValueArguments=false, shortName=VisibleForTesting]
        KotlinStub$CONSTRUCTOR_CALLEE
          KotlinStub$TYPE_REFERENCE
            KotlinStub$USER_TYPE
              KotlinStub$USER_TYPE
                KotlinStub$USER_TYPE
                  KotlinStub$USER_TYPE
                    KotlinStub$REFERENCE_EXPRESSION[referencedName=android]
                  KotlinStub$REFERENCE_EXPRESSION[referencedName=support]
                KotlinStub$REFERENCE_EXPRESSION[referencedName=annotation]
              KotlinStub$REFERENCE_EXPRESSION[referencedName=VisibleForTesting]
    KotlinStub$TYPE_REFERENCE
      KotlinStub$USER_TYPE
        KotlinStub$USER_TYPE
          KotlinStub$USER_TYPE
            KotlinStub$REFERENCE_EXPRESSION[referencedName=android]
          KotlinStub$REFERENCE_EXPRESSION[referencedName=os]
        KotlinStub$REFERENCE_EXPRESSION[referencedName=Looper]
    KotlinStub$VALUE_PARAMETER_LIST
      KotlinStub$VALUE_PARAMETER[fqName=null, hasDefaultValue=false, hasValOrVar=false, isMutable=false, name=async]
        KotlinStub$TYPE_REFERENCE
          KotlinStub$USER_TYPE
            KotlinStub$USER_TYPE
              KotlinStub$REFERENCE_EXPRESSION[referencedName=kotlin]
            KotlinStub$REFERENCE_EXPRESSION[referencedName=Boolean]
    KotlinStub$TYPE_REFERENCE
      KotlinStub$USER_TYPE
        KotlinStub$USER_TYPE
          KotlinStub$USER_TYPE
            KotlinStub$REFERENCE_EXPRESSION[referencedName=android]
          KotlinStub$REFERENCE_EXPRESSION[referencedName=os]
        KotlinStub$REFERENCE_EXPRESSION[referencedName=Handler]
```
</details>

File `stubTreeFromIndex.txt`:

<details>
```log
PsiJetFileStubImpl[package=kotlinx.coroutines.experimental.android]
  KotlinStub$PACKAGE_DIRECTIVE
    KotlinStub$DOT_QUALIFIED_EXPRESSION
      KotlinStub$DOT_QUALIFIED_EXPRESSION
        KotlinStub$DOT_QUALIFIED_EXPRESSION
          KotlinStub$REFERENCE_EXPRESSION[referencedName=kotlinx]
          KotlinStub$REFERENCE_EXPRESSION[referencedName=coroutines]
        KotlinStub$REFERENCE_EXPRESSION[referencedName=experimental]
      KotlinStub$REFERENCE_EXPRESSION[referencedName=android]
  KotlinStub$IMPORT_LIST
  KotlinStub$PROPERTY[fqName=kotlinx.coroutines.experimental.android.MAX_DELAY, hasDelegate=false, hasDelegateExpression=false, hasInitializer=false, hasReturnTypeRef=true, isExtension=false, isTopLevel=true, isVar=false, name=MAX_DELAY]
    KotlinStub$MODIFIER_LIST[private const]
    KotlinStub$TYPE_REFERENCE
      KotlinStub$USER_TYPE
        KotlinStub$USER_TYPE
          KotlinStub$REFERENCE_EXPRESSION[referencedName=kotlin]
        KotlinStub$REFERENCE_EXPRESSION[referencedName=Long]
  KotlinStub$PROPERTY[fqName=kotlinx.coroutines.experimental.android.Main, hasDelegate=false, hasDelegateExpression=false, hasInitializer=false, hasReturnTypeRef=true, isExtension=false, isTopLevel=true, isVar=false, name=Main]
    KotlinStub$MODIFIER_LIST[internal]
      KotlinStub$ANNOTATION_ENTRY[hasValueArguments=false, shortName=JvmField]
        KotlinStub$ANNOTATION_TARGET[useSiteTarget=FIELD]
        KotlinStub$CONSTRUCTOR_CALLEE
          KotlinStub$TYPE_REFERENCE
            KotlinStub$USER_TYPE
              KotlinStub$USER_TYPE
                KotlinStub$USER_TYPE
                  KotlinStub$REFERENCE_EXPRESSION[referencedName=kotlin]
                KotlinStub$REFERENCE_EXPRESSION[referencedName=jvm]
              KotlinStub$REFERENCE_EXPRESSION[referencedName=JvmField]
    KotlinStub$TYPE_REFERENCE
      KotlinStub$USER_TYPE
        KotlinStub$USER_TYPE
          KotlinStub$USER_TYPE
            KotlinStub$USER_TYPE
              KotlinStub$USER_TYPE
                KotlinStub$REFERENCE_EXPRESSION[referencedName=kotlinx]
              KotlinStub$REFERENCE_EXPRESSION[referencedName=coroutines]
            KotlinStub$REFERENCE_EXPRESSION[referencedName=experimental]
          KotlinStub$REFERENCE_EXPRESSION[referencedName=android]
        KotlinStub$REFERENCE_EXPRESSION[referencedName=HandlerDispatcher]
  KotlinStub$PROPERTY[fqName=kotlinx.coroutines.experimental.android.choreographer, hasDelegate=false, hasDelegateExpression=false, hasInitializer=false, hasReturnTypeRef=true, isExtension=false, isTopLevel=true, isVar=true, name=choreographer]
    KotlinStub$MODIFIER_LIST[private]
    KotlinStub$TYPE_REFERENCE
      KotlinStub$NULLABLE_TYPE
        KotlinStub$USER_TYPE
          KotlinStub$USER_TYPE
            KotlinStub$USER_TYPE
              KotlinStub$REFERENCE_EXPRESSION[referencedName=android]
            KotlinStub$REFERENCE_EXPRESSION[referencedName=view]
          KotlinStub$REFERENCE_EXPRESSION[referencedName=Choreographer]
  KotlinStub$PROPERTY[fqName=kotlinx.coroutines.experimental.android.mainHandler, hasDelegate=false, hasDelegateExpression=false, hasInitializer=false, hasReturnTypeRef=true, isExtension=false, isTopLevel=true, isVar=false, name=mainHandler]
    KotlinStub$MODIFIER_LIST[internal]
    KotlinStub$TYPE_REFERENCE
      KotlinStub$USER_TYPE
        KotlinStub$USER_TYPE
          KotlinStub$USER_TYPE
            KotlinStub$REFERENCE_EXPRESSION[referencedName=android]
          KotlinStub$REFERENCE_EXPRESSION[referencedName=os]
        KotlinStub$REFERENCE_EXPRESSION[referencedName=Handler]
  KotlinStub$PROPERTY[fqName=kotlinx.coroutines.experimental.android.Main, hasDelegate=false, hasDelegateExpression=false, hasInitializer=false, hasReturnTypeRef=true, isExtension=true, isTopLevel=true, isVar=false, name=Main]
    KotlinStub$MODIFIER_LIST[public]
      KotlinStub$ANNOTATION_ENTRY[hasValueArguments=false, shortName=JvmField]
        KotlinStub$ANNOTATION_TARGET[useSiteTarget=FIELD]
        KotlinStub$CONSTRUCTOR_CALLEE
          KotlinStub$TYPE_REFERENCE
            KotlinStub$USER_TYPE
              KotlinStub$USER_TYPE
                KotlinStub$USER_TYPE
                  KotlinStub$REFERENCE_EXPRESSION[referencedName=kotlin]
                KotlinStub$REFERENCE_EXPRESSION[referencedName=jvm]
              KotlinStub$REFERENCE_EXPRESSION[referencedName=JvmField]
    KotlinStub$TYPE_REFERENCE
      KotlinStub$USER_TYPE
        KotlinStub$USER_TYPE
          KotlinStub$USER_TYPE
            KotlinStub$USER_TYPE
              KotlinStub$REFERENCE_EXPRESSION[referencedName=kotlinx]
            KotlinStub$REFERENCE_EXPRESSION[referencedName=coroutines]
          KotlinStub$REFERENCE_EXPRESSION[referencedName=experimental]
        KotlinStub$REFERENCE_EXPRESSION[referencedName=Dispatchers]
    KotlinStub$TYPE_REFERENCE
      KotlinStub$USER_TYPE
        KotlinStub$USER_TYPE
          KotlinStub$USER_TYPE
            KotlinStub$USER_TYPE
              KotlinStub$USER_TYPE
                KotlinStub$REFERENCE_EXPRESSION[referencedName=kotlinx]
              KotlinStub$REFERENCE_EXPRESSION[referencedName=coroutines]
            KotlinStub$REFERENCE_EXPRESSION[referencedName=experimental]
          KotlinStub$REFERENCE_EXPRESSION[referencedName=android]
        KotlinStub$REFERENCE_EXPRESSION[referencedName=HandlerDispatcher]
  KotlinStub$FUN[fqName=kotlinx.coroutines.experimental.android.awaitFrame, hasBlockBody=true, hasBody=true, hasTypeParameterListBeforeFunctionName=false, isExtension=false, isTopLevel=true, mayHaveContract=false, name=awaitFrame]
    KotlinStub$MODIFIER_LIST[public suspend]
    KotlinStub$VALUE_PARAMETER_LIST
    KotlinStub$TYPE_REFERENCE
      KotlinStub$USER_TYPE
        KotlinStub$USER_TYPE
          KotlinStub$REFERENCE_EXPRESSION[referencedName=kotlin]
        KotlinStub$REFERENCE_EXPRESSION[referencedName=Long]
  KotlinStub$FUN[fqName=kotlinx.coroutines.experimental.android.postFrameCallback, hasBlockBody=true, hasBody=true, hasTypeParameterListBeforeFunctionName=false, isExtension=false, isTopLevel=true, mayHaveContract=false, name=postFrameCallback]
    KotlinStub$MODIFIER_LIST[private]
    KotlinStub$VALUE_PARAMETER_LIST
      KotlinStub$VALUE_PARAMETER[fqName=null, hasDefaultValue=false, hasValOrVar=false, isMutable=false, name=choreographer]
        KotlinStub$TYPE_REFERENCE
          KotlinStub$USER_TYPE
            KotlinStub$USER_TYPE
              KotlinStub$USER_TYPE
                KotlinStub$REFERENCE_EXPRESSION[referencedName=android]
              KotlinStub$REFERENCE_EXPRESSION[referencedName=view]
            KotlinStub$REFERENCE_EXPRESSION[referencedName=Choreographer]
      KotlinStub$VALUE_PARAMETER[fqName=null, hasDefaultValue=false, hasValOrVar=false, isMutable=false, name=cont]
        KotlinStub$TYPE_REFERENCE
          KotlinStub$USER_TYPE
            KotlinStub$USER_TYPE
              KotlinStub$USER_TYPE
                KotlinStub$USER_TYPE
                  KotlinStub$REFERENCE_EXPRESSION[referencedName=kotlinx]
                KotlinStub$REFERENCE_EXPRESSION[referencedName=coroutines]
              KotlinStub$REFERENCE_EXPRESSION[referencedName=experimental]
            KotlinStub$REFERENCE_EXPRESSION[referencedName=CancellableContinuation]
            KotlinStub$TYPE_ARGUMENT_LIST
              KotlinStub$TYPE_PROJECTION[projectionKind=NONE]
                KotlinStub$TYPE_REFERENCE
                  KotlinStub$USER_TYPE
                    KotlinStub$USER_TYPE
                      KotlinStub$REFERENCE_EXPRESSION[referencedName=kotlin]
                    KotlinStub$REFERENCE_EXPRESSION[referencedName=Long]
    KotlinStub$TYPE_REFERENCE
      KotlinStub$USER_TYPE
        KotlinStub$USER_TYPE
          KotlinStub$REFERENCE_EXPRESSION[referencedName=kotlin]
        KotlinStub$REFERENCE_EXPRESSION[referencedName=Unit]
  KotlinStub$FUN[fqName=kotlinx.coroutines.experimental.android.updateChoreographerAndPostFrameCallback, hasBlockBody=true, hasBody=true, hasTypeParameterListBeforeFunctionName=false, isExtension=false, isTopLevel=true, mayHaveContract=false, name=updateChoreographerAndPostFrameCallback]
    KotlinStub$MODIFIER_LIST[private]
    KotlinStub$VALUE_PARAMETER_LIST
      KotlinStub$VALUE_PARAMETER[fqName=null, hasDefaultValue=false, hasValOrVar=false, isMutable=false, name=cont]
        KotlinStub$TYPE_REFERENCE
          KotlinStub$USER_TYPE
            KotlinStub$USER_TYPE
              KotlinStub$USER_TYPE
                KotlinStub$USER_TYPE
                  KotlinStub$REFERENCE_EXPRESSION[referencedName=kotlinx]
                KotlinStub$REFERENCE_EXPRESSION[referencedName=coroutines]
              KotlinStub$REFERENCE_EXPRESSION[referencedName=experimental]
            KotlinStub$REFERENCE_EXPRESSION[referencedName=CancellableContinuation]
            KotlinStub$TYPE_ARGUMENT_LIST
              KotlinStub$TYPE_PROJECTION[projectionKind=NONE]
                KotlinStub$TYPE_REFERENCE
                  KotlinStub$USER_TYPE
                    KotlinStub$USER_TYPE
                      KotlinStub$REFERENCE_EXPRESSION[referencedName=kotlin]
                    KotlinStub$REFERENCE_EXPRESSION[referencedName=Long]
    KotlinStub$TYPE_REFERENCE
      KotlinStub$USER_TYPE
        KotlinStub$USER_TYPE
          KotlinStub$REFERENCE_EXPRESSION[referencedName=kotlin]
        KotlinStub$REFERENCE_EXPRESSION[referencedName=Unit]
  KotlinStub$FUN[fqName=kotlinx.coroutines.experimental.android.asCoroutineDispatcher, hasBlockBody=true, hasBody=true, hasTypeParameterListBeforeFunctionName=false, isExtension=true, isTopLevel=true, mayHaveContract=false, name=asCoroutineDispatcher]
    KotlinStub$MODIFIER_LIST[public]
      KotlinStub$ANNOTATION_ENTRY[hasValueArguments=false, shortName=JvmName]
        KotlinStub$CONSTRUCTOR_CALLEE
          KotlinStub$TYPE_REFERENCE
            KotlinStub$USER_TYPE
              KotlinStub$USER_TYPE
                KotlinStub$USER_TYPE
                  KotlinStub$REFERENCE_EXPRESSION[referencedName=kotlin]
                KotlinStub$REFERENCE_EXPRESSION[referencedName=jvm]
              KotlinStub$REFERENCE_EXPRESSION[referencedName=JvmName]
      KotlinStub$ANNOTATION_ENTRY[hasValueArguments=false, shortName=JvmOverloads]
        KotlinStub$CONSTRUCTOR_CALLEE
          KotlinStub$TYPE_REFERENCE
            KotlinStub$USER_TYPE
              KotlinStub$USER_TYPE
                KotlinStub$USER_TYPE
                  KotlinStub$REFERENCE_EXPRESSION[referencedName=kotlin]
                KotlinStub$REFERENCE_EXPRESSION[referencedName=jvm]
              KotlinStub$REFERENCE_EXPRESSION[referencedName=JvmOverloads]
    KotlinStub$TYPE_REFERENCE
      KotlinStub$USER_TYPE
        KotlinStub$USER_TYPE
          KotlinStub$USER_TYPE
            KotlinStub$REFERENCE_EXPRESSION[referencedName=android]
          KotlinStub$REFERENCE_EXPRESSION[referencedName=os]
        KotlinStub$REFERENCE_EXPRESSION[referencedName=Handler]
    KotlinStub$VALUE_PARAMETER_LIST
      KotlinStub$VALUE_PARAMETER[fqName=null, hasDefaultValue=false, hasValOrVar=false, isMutable=false, name=name]
        KotlinStub$TYPE_REFERENCE
          KotlinStub$NULLABLE_TYPE
            KotlinStub$USER_TYPE
              KotlinStub$USER_TYPE
                KotlinStub$REFERENCE_EXPRESSION[referencedName=kotlin]
              KotlinStub$REFERENCE_EXPRESSION[referencedName=String]
    KotlinStub$TYPE_REFERENCE
      KotlinStub$USER_TYPE
        KotlinStub$USER_TYPE
          KotlinStub$USER_TYPE
            KotlinStub$USER_TYPE
              KotlinStub$USER_TYPE
                KotlinStub$REFERENCE_EXPRESSION[referencedName=kotlinx]
              KotlinStub$REFERENCE_EXPRESSION[referencedName=coroutines]
            KotlinStub$REFERENCE_EXPRESSION[referencedName=experimental]
          KotlinStub$REFERENCE_EXPRESSION[referencedName=android]
        KotlinStub$REFERENCE_EXPRESSION[referencedName=HandlerDispatcher]
  KotlinStub$FUN[fqName=kotlinx.coroutines.experimental.android.asHandler, hasBlockBody=true, hasBody=true, hasTypeParameterListBeforeFunctionName=false, isExtension=true, isTopLevel=true, mayHaveContract=false, name=asHandler]
    KotlinStub$MODIFIER_LIST[internal]
      KotlinStub$ANNOTATION_ENTRY[hasValueArguments=false, shortName=VisibleForTesting]
        KotlinStub$CONSTRUCTOR_CALLEE
          KotlinStub$TYPE_REFERENCE
            KotlinStub$USER_TYPE
              KotlinStub$USER_TYPE
                KotlinStub$USER_TYPE
                  KotlinStub$USER_TYPE
                    KotlinStub$REFERENCE_EXPRESSION[referencedName=android]
                  KotlinStub$REFERENCE_EXPRESSION[referencedName=support]
                KotlinStub$REFERENCE_EXPRESSION[referencedName=annotation]
              KotlinStub$REFERENCE_EXPRESSION[referencedName=VisibleForTesting]
    KotlinStub$TYPE_REFERENCE
      KotlinStub$USER_TYPE
        KotlinStub$USER_TYPE
          KotlinStub$USER_TYPE
            KotlinStub$REFERENCE_EXPRESSION[referencedName=android]
          KotlinStub$REFERENCE_EXPRESSION[referencedName=os]
        KotlinStub$REFERENCE_EXPRESSION[referencedName=Looper]
    KotlinStub$VALUE_PARAMETER_LIST
      KotlinStub$VALUE_PARAMETER[fqName=null, hasDefaultValue=false, hasValOrVar=false, isMutable=false, name=async]
        KotlinStub$TYPE_REFERENCE
          KotlinStub$USER_TYPE
            KotlinStub$USER_TYPE
              KotlinStub$REFERENCE_EXPRESSION[referencedName=kotlin]
            KotlinStub$REFERENCE_EXPRESSION[referencedName=Boolean]
    KotlinStub$TYPE_REFERENCE
      KotlinStub$USER_TYPE
        KotlinStub$USER_TYPE
          KotlinStub$USER_TYPE
            KotlinStub$REFERENCE_EXPRESSION[referencedName=android]
          KotlinStub$REFERENCE_EXPRESSION[referencedName=os]
        KotlinStub$REFERENCE_EXPRESSION[referencedName=Handler]
```
</details>

### PR DESCRIPTION
**Pull request by qwwdfsad**
Main thread dispatchers are grouped under Dispatchers object and are discoverable via ServiceLoader
  * Dispatchers.Main can be consistently used and easily discovered, its implementation is discovered with ServiceLoader
  * It allows us to add iOS Dispatchers.Main implementation in the future thus opening the door for multiplatform UI-dispatched code
  * Workaround for #626, now Android users can start a migration to RC coroutines

Fixed #626

### CODE REVIEW

File: ui/kotlinx-coroutines-android/src/HandlerDispatcher.kt [hunk 1]
```diff
@@ -33,7 +35,11 @@ public sealed class HandlerDispatcher : CoroutineDispatcher(), Delay {
      * **Note: This is an experimental api.** Semantics of this dispatcher may change in the future.
      */
     @ExperimentalCoroutinesApi
-    public abstract val immediate: HandlerDispatcher
+    public abstract override val immediate: HandlerDispatcher
+}
+
+internal class AndroidDispatcherFactory : MainDispatcherFactory {
```
Comment (JakeWharton) [inline ui/kotlinx-coroutines-android/src/HandlerDispatcher.kt]: This class needs annotated with `@Keep` or it will be removed automatically as being unused for all R8/ProGuard users requiring manual configuration.

Comment (qwwdfsad) [reply ui/kotlinx-coroutines-android/src/HandlerDispatcher.kt]: Good catch, thank you.

>I suspect this might cause start performance regression for all Android users based on putting ServiceLoader usage on the critical path

`mainDispatcher` is initialized only once when `Dispatchers` object is instantiated, it is not on the critical path.

Comment (JakeWharton) [reply ui/kotlinx-coroutines-android/src/HandlerDispatcher.kt]: I suspect most Android apps will launch _something_ during startup which requires a `Dispatchers.Main` reference and will force initialization.

Perhaps we can get R8 to rewrite any `ServiceLoader` usage with a constant array determined at compile-time. This could avoid the need for `@Keep` on the implementations as well.

Comment (qwwdfsad) [reply ui/kotlinx-coroutines-android/src/HandlerDispatcher.kt]: I got your point. Is an access to `ServiceLoader` a regression significant enough to postpone this change?

Comment (JakeWharton) [reply ui/kotlinx-coroutines-android/src/HandlerDispatcher.kt]: I don't know what the impact is off-hand. Android definitely isn't optimized for this case though which is why it has its own resource and asset system. I can measure, but it won't be until Friday at the earliest.

Comment (qwwdfsad) [reply ui/kotlinx-coroutines-android/src/HandlerDispatcher.kt]: We will merge it then, mostly to stabilize our API.
If you (or anyone else) report a significant regression, we will rework this part without changing the API (e.g. with `Class.forName` or any other hack like this)

**Comment by kirill-grouchnikov** [comment]
How will this work in hybrid Swing-JavaFX apps?

**Comment by qwwdfsad** [comment]
@kirill-grouchnikov JavaFx will win as a main dispatcher.
In such apps you should directly use `Dispatchers.Swing` and `Dispatchers.JavaFx`
