### PR TITLE
Fix newSingleThreadContext awaiting cancelled scheduled coroutines

### LINKED ISSUE #3768: newSingleThreadContext on Native can't close until timeouts finish
Reported in the Kotlin Slack originally.

Simplified reproducer:
```kotlin
    @Test
    fun timeoutAffectsClosing() = runBlocking {
        val disp: CloseableCoroutineDispatcher = newSingleThreadContext("my-test")
        val result = withContext(disp) {
            // Disabling the inner timeout will make it work correctly
            withTimeout(30.seconds) {
                "Hello"
            }
        }
        println(result) // Print "Hello"
        disp.close()
        println("Dispatcher closed: $disp") // takes 30 seconds to get here
    }
```

### PR DESCRIPTION
**Pull request by dkhalanskyjb**
Before the change, the Worker is not notified about its work being cancelled, due to no API being present for that.
We work around the issue by checking every 100 milliseconds whether cancellation happened.

Fixes #3768

### CODE REVIEW

**Comment by dkhalanskyjb** [comment]
Ah, ok, I get it, it's because this dispatcher is reused for the `DefaultExecutor`.

**Comment by dkhalanskyjb** [comment]
Maybe it makes sense to have `WorkerDispatcher` be only for the `DefaultExecutor` and have `newSingleThreadContext` be `newFixedThreadPoolContext(1)`, like on the JVM.

File: kotlinx-coroutines-core/native/src/MultithreadedDispatchers.kt [hunk 1]
```diff
@@ -52,10 +55,24 @@ internal class WorkerDispatcher(name: String) : CloseableCoroutineDispatcher(),
             override fun dispose() {
                 disposableHolder.value = null
             }
+
+            fun isDisposed() = disposableHolder.value == null
+        }
+
+        fun Worker.runAfterDelay(block: DisposableBlock, targetMoment: TimeMark) {
+            if (block.isDisposed()) return
+            val durationUntilTarget = -targetMoment.elapsedNow()
```
Comment (qwwdfsad) [inline kotlinx-coroutines-core/native/src/MultithreadedDispatchers.kt:64]: Was a bit confused at the beginning when looking at documentation only, have filed https://youtrack.jetbrains.com/issue/KT-59044/Improve-various-aspects-of-TimeSource-documentation

Comment (qwwdfsad) [reply kotlinx-coroutines-core/native/src/MultithreadedDispatchers.kt:64]: Probably we can ignore "infinity" problem for now -- such check would be untestable anyway

**Review by qwwdfsad — APPROVED** [review]
Nice one!

I'm onboard with making `WorkerDispatcher` available only for `DefaultExecutor`

File: kotlinx-coroutines-core/native/src/MultithreadedDispatchers.kt [hunk 2]
```diff
@@ -52,10 +55,24 @@ internal class WorkerDispatcher(name: String) : CloseableCoroutineDispatcher(),
...
+            if (durationUntilTarget > quantum) {
+                executeAfter(quantum.inWholeMicroseconds) { runAfterDelay(block, targetMoment) }
+            } else {
+                executeAfter(durationUntilTarget.inWholeMicroseconds, block)
+            }
         }
 
         val disposableBlock = DisposableBlock(block)
-        worker.executeAfter(timeMillis.toMicrosSafe(), disposableBlock)
+        val targetMoment = TimeSource.Monotonic.markNow() + timeMillis.milliseconds
```
[the remark this answers is not in the document]
Comment (qwwdfsad) [reply kotlinx-coroutines-core/native/src/MultithreadedDispatchers.kt:69]: Still unused

**Review by qwwdfsad — CHANGES_REQUESTED** [review]
Our build started flaking consistently after the change, could you please take a look?
Otherwise LGTM

**Comment by dkhalanskyjb** [comment]
The first build failure was on me, an API dump changed, which I later fixed, but the second one seems to be just Windows doing its thing, no?

**Comment by dkhalanskyjb** [comment]
Ah, no, I see now that something's off.

**Comment by dkhalanskyjb** [comment]
Who knew? This was an actual bug. Turns out `executeAfter` doesn't crashes on negative numbers.

**Review by qwwdfsad — APPROVED** [review]
