### PR TITLE
Properly recover exceptions when they are constructed from 'Throwable…

### LINKED ISSUE #3714: recoverStackTrace causes nested exceptions
**Describe the bug**

When throwing an exception in a coroutine scope it sometimes becomes nested one level too deep in the enclosing exception.

For example, if I throw a: `TestException(IllegalStateException("test"))` (a TestException with a cause of IllegalStateException with a message), then the coroutine scope will throw an exception that is: `TestException(TestException(IllegalStateException("test")))`.

**Provide a Reproducer**

The following test will fail as a result of this bug:

```
@Test
fun testNestedException() = runTest {
    val result = runCatching {
        coroutineScope<Unit> {
            throw NestedException(IllegalStateException("ERROR"))
        }
    }
    val ex = result.exceptionOrNull() ?: error("Expected to fail")
    assertTrue(ex is NestedException)
    assertTrue(ex.cause is IllegalStateException)
    assertEquals("ERROR", (ex.cause as IllegalStateException).message)
}

class NestedException : RuntimeException {
    constructor(message: String) : super(message)
    constructor(cause: Throwable) : super(cause)
    constructor() : super()
}
```

I can get this test to not fail by changing the order of the constructors in the class to:

```
class NestedException : RuntimeException {
    constructor(cause: Throwable) : super(cause)
    constructor(message: String) : super(message)
    constructor() : super()
}
```
But I don't think this is actually a good solution as it shouldn't matter the order of the constructors in my exception, it should work the same way regardless.

I think the issue is at [this line](https://github.com/Kotlin/kotlinx.coroutines/blob/3fc1c20a87a689c09f062afc9e3ac347829d29f7/kotlinx-coroutines-core/jvm/src/internal/ExceptionsConstructor.kt#L30) where the wrong constructor is being selected (the string constructor instead of the cause constructor).

### PR DESCRIPTION
**Pull request by qwwdfsad**
…(cause)' constructor.

And restore the original behaviour. After #1631 this constructor's recovery mechanism was broken because 'Throwable(cause)' changes the message to be equal to 'cause.toString()' which isn't equal to the original message.

Also, make reflective constructor choice independable from source-code order

Fixes #3714

### CODE REVIEW

File: kotlinx-coroutines-core/jvm/src/internal/StackTraceRecovery.kt [hunk 1]
```diff
@@ -84,9 +84,6 @@ private fun <E : Throwable> recoverFromStackFrame(exception: E, continuation: Co
 
 private fun <E : Throwable> tryCopyAndVerify(exception: E): E? {
```
Comment (dkhalanskyjb) [inline kotlinx-coroutines-core/jvm/src/internal/StackTraceRecovery.kt:85]: This method is now exactly the same as just `tryCopyException`.

File: kotlinx-coroutines-core/jvm/src/internal/ExceptionsConstructor.kt [hunk 2]
```diff
@@ -32,13 +32,29 @@ internal fun <E : Throwable> tryCopyException(exception: E): E? {
...
+        // (m) -> 2
+        // (c) -> 1
+        // () -> 0
+        val params = it.parameterTypes // cloned array
+        when (params.size) {
+            2 -> 3
+            1 -> if (params[0] == String::class.java) 2 else 1
+            0 -> 0
+            else -> -1
+        }
```
Comment (dkhalanskyjb) [inline kotlinx-coroutines-core/jvm/src/internal/ExceptionsConstructor.kt:55]: I agree with the change, but I'd like to propose a stylistic edit: https://gist.github.com/dkhalanskyjb/2c2b4362920a01aafb3955216fd0e501 It makes the code more straightforward, in my view, but leads to calls to `safeCtor` even for constructors that don't get chosen in the end.

Comment (qwwdfsad) [reply kotlinx-coroutines-core/jvm/src/internal/ExceptionsConstructor.kt:62]: Sure, works for me.
Calls to `createConstructor` are cached, so it should not be a problem.

I've applied your patch **and** removed `inline` from `safeCtor` to reduce the size of the classfile (-25%)

**Review by dkhalanskyjb — APPROVED** [review]
