### PR TITLE
Do not report exceptions raised in CoroutineDispatcher.dispatch as in…

### LINKED ISSUE #4091: kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for CancellableContinuation
**Describe the bug**

The following test works on Android, but crashes on iOS:

```
    @Test
    fun reproduce() = runBlocking {
        val dispatcher = newSingleThreadContext("MyDispatcher")

        launch(dispatcher) {
            try {
                withContext(Dispatchers.Default) {
                    println("!!! before delay")
                    delay(1000)
                    println("!!! after delay")
                }
            } catch (e: Exception) {
                println("!!! Ignored exception: $e")
            }
        }

        delay(200)

        println("!!! before close")
        dispatcher.close()
        println("!!! after close")
        println("!!! DONE !!!")
    }
```

Output form Android Emulator Arm64 (no crashes, everything works as expected):
```
        I  !!! before delay
        I  !!! before close
        I  !!! after close
        I  !!! DONE !!!
        I  !!! after delay
        I  !!! Ignored exception: java.util.concurrent.CancellationException: The task was rejected

run finished: 1 tests, 0 failed, 0 ignored
```

Output from iOS Simulator Arm64 (test crashed):
```
1 test completed, 1 failed
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':sync-android-kt:iosSimulatorArm64Test'.
> Test running process exited unexpectedly.
  Current test: reproduce
  Process output:
  !!! before delay
  !!! before close
  !!! after close
  !!! DONE !!!
  !!! after delay
  kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for CancellableContinuation(DispatchedContinuation[DarwinGlobalQueueDispatcher@53c0308, Continuation @ 6]){Completed}@79400a0. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
      at 0   test.kexe                           0x102735883        kfun:kotlin.Error#<init>(kotlin.String?;kotlin.Throwable?){} + 143 (/opt/buildAgent/work/2fed3917837e7e79/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/Exceptions.kt:14:63)
      at 1   test.kexe                           0x10298ba27        kfun:kotlinx.coroutines.CoroutinesInternalError#<init>(kotlin.String;kotlin.Throwable){} + 123 (/opt/buildAgent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/common/src/Exceptions.common.kt:23:77)
      at 2   test.kexe                           0x1029f242f        kfun:kotlinx.coroutines.DispatchedTask#handleFatalException(kotlin.Throwable?;kotlin.Throwable?){} + 755 (/opt/buildAgent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/common/src/internal/DispatchedTask.kt:142:22)
      at 3   test.kexe                           0x1029f2113        kfun:kotlinx.coroutines.DispatchedTask#run(){} + 2455 (/opt/buildAgent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/common/src/internal/DispatchedTask.kt:113:13)
      at 4   test.kexe                           0x102a1b9bb        kfun:kotlinx.coroutines.Runnable#run(){}-trampoline + 91 (/opt/buildAgent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/native/src/Runnable.kt:10:19)
      at 5   test.kexe                           0x102a17067        kfun:kotlinx.coroutines.DarwinGlobalQueueDispatcher.dispatch$lambda$0#internal + 119 (/opt/buildAgent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/nativeDarwin/src/Dispatchers.kt:22:23)
      at 6   test.kexe                           0x102a170c3        kfun:kotlinx.coroutines.DarwinGlobalQueueDispatcher.$dispatch$lambda$0$FUNCTION_REFERENCE$0.invoke#internal + 71 (/opt/buildAgent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/nativeDarwin/src/Dispatchers.kt:21:13)
      at 7   test.kexe                           0x102a17193        kfun:kotlinx.coroutines.DarwinGlobalQueueDispatcher.$dispatch$lambda$0$FUNCTION_REFERENCE$0.$<bridge-UNN>invoke(){}#internal + 71 (/opt/buildAgent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/nativeDarwin/src/Dispatchers.kt:21:13)
      at 8   test.kexe                           0x102865807        kfun:kotlin.Function0#invoke(){}1:0-trampoline + 99 (/Users/teamcity/.gradle/daemon/8.2.1/[K][Suspend]Functions:1:1)
      at 9   test.kexe                           0x102a18d13        _6f72672e6a6574627261696e732e6b6f746c696e783a6b6f746c696e782d636f726f7574696e65732d636f72652f6f70742f6275696c644167656e742f776f726b2f343465633665383530643563363366302f6b6f746c696e782d636f726f7574696e65732d636f72652f6e617469766544617277696e2f7372632f44697370617463686572732e6b74_knbridge8 + 191 (/opt/buildAgent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/nativeDarwin/src/Dispatchers.kt:21:13)
      at 10  libdispatch.dylib                   0x18016b4f3        _dispatch_call_block_and_release + 23 
      at 11  libdispatch.dylib                   0x18016cd3b        _dispatch_client_callout + 15 
      at 12  libdispatch.dylib                   0x18017f5d3        _dispatch_root_queue_drain + 1075 
      at 13  libdispatch.dylib                   0x18017fd57        _dispatch_worker_thread2 + 231 
      at 14  libsystem_pthread.dylib             0x1045cf8e7        _pthread_wqthread + 223 
      at 15  libsystem_pthread.dylib             0x1045ce6e3        start_wqthread + 7 
      Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [DispatchedCoroutine{Completed}@4661750, DarwinGlobalQueueDispatcher@53c0308]
          at 0   test.kexe                           0x10273c19b        kfun:kotlin.Throwable#<init>(kotlin.String?){} + 119 (/opt/buildAgent/work/2fed3917837e7e79/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/Throwable.kt:28:37)
          at 1   test.kexe                           0x102735977        kfun:kotlin.Exception#<init>(kotlin.String?){} + 115 (/opt/buildAgent/work/2fed3917837e7e79/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/Exceptions.kt:23:44)
  Uncaught Kotlin exception:         at 2   test.kexe                           0x102735b97        kfun:kotlin.RuntimeException#<init>(kotlin.String?){} + 115 (/opt/buildAgent/work/2fed3917837e7e79/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/Exceptions.kt:34:44)
          at 3   test.kexe                           0x102a15593        kfun:kotlinx.coroutines.internal.DiagnosticCoroutineContextException#<init>(kotlin.coroutines.CoroutineContext){} + 167 (/opt/buildAgent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/native/src/internal/CoroutineExceptionHandlerImpl.kt:27:5)
          at 4   test.kexe                           0x1029ee17f        kfun:kotlinx.coroutines.internal#handleUncaughtCoroutineException(kotlin.coroutines.CoroutineContext;kotlin.Throwable){} + 647 (/opt/buildAgent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/common/src/internal/CoroutineExceptionHandlerImpl.common.kt:43:33)
          at 5   test.kexe                           0x1029843ab        kfun:kotlinx.coroutines#handleCoroutineException(kotlin.coroutines.CoroutineContext;kotlin.Throwable){} + 515 (/opt/buildAgent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt:28:5)
          at 6   test.kexe                           0x1029f247b        kfun:kotlinx.coroutines.DispatchedTask#handleFatalException(kotlin.Throwable?;kotlin.Throwable?){} + 831 (/opt/buildAgent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/common/src/internal/DispatchedTask.kt:144:9)
          at 7   test.kexe                           0x1029f2113        kfun:kotlinx.coroutines.DispatchedTask#run(){} + 2455 (/opt/buildAgent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/common/src/internal/DispatchedTask.kt:113:13)
          ... and 12 more common stack frames skipped
  Caused by: kotlin.IllegalStateException: Dispatcher MyDispatcher was closed, attempted to schedule: DispatchedContinuation[MultiWorkerDispatcher@4584120, Continuation @ 7]
      at 0   test.kexe                           0x10273c19b        kfun:kotlin.Throwable#<init>(kotlin.String?){} + 119 (/opt/buildAgent/work/2fed3917837e7e79/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/Throwable.kt:28:37)
      at 1   test.kexe                           0x102735977        kfun:kotlin.Exception#<init>(kotlin.String?){} + 115 (/opt/buildAgent/work/2fed3917837e7e79/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/Exceptions.kt:23:44)
      at 2   test.kexe                           0x102735b97        kfun:kotlin.RuntimeException#<init>(kotlin.String?){} + 115 (/opt/buildAgent/work/2fed3917837e7e79/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/Exceptions.kt:34:44)
      at 3   test.kexe                           0x1027361bf        kfun:kotlin.IllegalStateException#<init>(kotlin.String?){} + 115 (/opt/buildAgent/work/2fed3917837e7e79/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/Exceptions.kt:70:44)
      at 4   test.kexe                           0x102a1243f        kfun:kotlinx.coroutines.MultiWorkerDispatcher.dispatch#internal + 819 (/opt/buildAgent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/native/src/MultithreadedDispatchers.kt:128:23)
      at 5   test.kexe                           0x102a1aad7        kfun:kotlinx.coroutines.CoroutineDispatcher#dispatch(kotlin.coroutines.CoroutineContext;kotlinx.coroutines.Runnable){}-trampoline + 67 (/opt/buildAgent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/common/src/CoroutineDispatcher.kt:<unknown>)
      at 6   test.kexe                           0x1029f08f7        kfun:kotlinx.coroutines.internal#resumeCancellableWith__at__kotlin.coroutines.Continuation<0:0>(kotlin.Result<0:0>;kotlin.Function1<kotlin.Throwable,kotlin.Unit>?){0§<kotlin.Any?>} + 1019 (/opt/buildAgent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/common/src/internal/DispatchedContinuation.kt:278:64)
      at 7   test.kexe                           0x1029f0f7b        kfun:kotlinx.coroutines.internal#resumeCancellableWith$default__at__kotlin.coroutines.Continuation<0:0>(kotlin.Result<0:0>;kotlin.Function1<kotlin.Throwable,kotlin.Unit>?;kotlin.Int){0§<kotlin.Any?>} + 287 (/opt/buildAgent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/common/src/internal/DispatchedContinuation.kt:274:8)
      at 8   test.kexe                           0x102978e77        kfun:kotlinx.coroutines.DispatchedCoroutine#afterResume(kotlin.Any?){} + 311 (/opt/buildAgent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/common/src/Builders.common.kt:257:29)
      at 9   test.kexe                           0x102a190ab        kfun:kotlinx.coroutines.AbstractCoroutine#afterResume(kotlin.Any?){}-trampoline + 59 (/opt/buildAgent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/common/src/AbstractCoroutine.kt:<unknown>)
      at 10  test.kexe                           0x102976a8b        kfun:kotlinx.coroutines.AbstractCoroutine#resumeWith(kotlin.Result<1:0>){} + 303 (/opt/buildAgent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/common/src/AbstractCoroutine.kt:99:9)
      at 11  test.kexe                           0x102868e03        kfun:kotlin.coroutines.Continuation#resumeWith(kotlin.Result<1:0>){}-trampoline + 99 (/opt/buildAgent/work/2fed3917837e7e79/kotlin/libraries/stdlib/src/kotlin/coroutines/Continuation.kt:26:12)
      at 12  test.kexe                           0x102740fd7        kfun:kotlin.coroutines.native.internal.BaseContinuationImpl#resumeWith(kotlin.Result<kotlin.Any?>){} + 1163 (/opt/buildAgent/work/2fed3917837e7e79/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/coroutines/ContinuationImpl.kt:43:32)
      at 13  test.kexe                           0x102868e03        kfun:kotlin.coroutines.Continuation#resumeWith(kotlin.Result<1:0>){}-trampoline + 99 (/opt/buildAgent/work/2fed3917837e7e79/kotlin/libraries/stdlib/src/kotlin/coroutines/Continuation.kt:26:12)
      at 14  test.kexe                           0x1029f1ed3        kfun:kotlinx.coroutines.DispatchedTask#run(){} + 1879 (/opt/buildAgent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/common/src/internal/DispatchedTask.kt:104:71)
      at 15  test.kexe                           0x102a1b9bb        kfun:kotlinx.coroutines.Runnable#run(){}-trampoline + 91 (/opt/buildAgent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/native/src/Runnable.kt:10:19)
      ... and 11 more common stack frames skipped
  Child process terminated with signal 6: Abort trap
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 1m 3s
```

Maybe the root cause is related to fact that on iOS `IllegalStateException` is thrown when flow returns from the `withContext(Dispatchers.Default)` section, in case of android the output above demonstrates that the `CancellationException` is thrown at the same place.

**Versions**

```
    androidGradlePluginVersion = "8.1.2"
    kotlinVersion = '1.9.23'
    kotlinCoroutinesVersion = "1.8.0"
    skieVersion = "0.6.2"
    
    classpath "com.android.tools.build:gradle:$androidGradlePluginVersion"
    classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"

    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlinVersion"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:$kotlinCoroutinesVersion"
    
    plugins {
      id 'org.jetbrains.kotlin.multiplatform'
      id 'com.android.library'
      id "co.touchlab.skie" version "$skieVersion"
    }

```

### PR DESCRIPTION
**Pull request by zuevmaxim**
…ternal errors

Fix #4091

### CODE REVIEW

File: kotlinx-coroutines-core/common/src/internal/DispatchedTask.kt [hunk 1]
```diff
@@ -213,3 +219,10 @@ internal inline fun DispatchedTask<*>.runUnconfinedEventLoop(
 internal inline fun Continuation<*>.resumeWithStackTrace(exception: Throwable) {
     resumeWith(Result.failure(recoverStackTrace(exception, this)))
 }
+
+/**
+ * This exception holds an exception raised in [CoroutineDispatcher.dispatch] method
+ *
+ * @see DispatchedContinuation.dispatchWithExceptionHandling
+ */
+internal class DispatchException(cause: Throwable) : Exception(cause)
```
[the remark this answers is not in the document]
Comment (dkhalanskyjb) [reply kotlinx-coroutines-core/common/src/internal/DispatchedTask.kt:228]: In theory, it is possible that the end user will see this exception. The simplest example:
```kotlin
val dispatcher = object: CoroutineDispatcher() {
    override fun dispatch(context: CoroutineContext, block: Runnable) {
        TODO("Not yet implemented")
    }

}
runBlocking {
    try {
        suspendCancellableCoroutine<Unit> { cont ->
            dispatcher.interceptContinuation(cont).resume(Unit)
        }
    } catch (e: Throwable) {
        println("Caught $e")
    }
}
```
This means that it's better to supply a diagnostic message, like, "a coroutine dispatcher threw an exception." It would also be nice to include the dispatcher (and possibly the rest of the coroutine context) in the message.

**Review by dkhalanskyjb — CHANGES_REQUESTED** [review]
This is a nice start, though a review of the other places where `dispatch`, `isDispatchNeeded`, and/or `intercepted()` happens shows that it's in general very easy to leave `kotlinx-coroutines` in an incorrect state if dispatchers throw: https://github.com/Kotlin/kotlinx.coroutines/issues/4209

If you're up for it, we can try to provide sensible behavior for dispatcher errors in all places as part of this pull request, or we can limit the scope to that one specific crash and leave the more robust and general solution for another time.

**Comment by dkhalanskyjb** [comment]
Historical note: we've discussed it internally and decided that #4209 is out of this PR's scope.

File: kotlinx-coroutines-core/common/src/internal/DispatchedTask.kt [hunk 2]
```diff
@@ -102,11 +103,14 @@ internal abstract class DispatchedTask<in T> internal constructor(
...
             }
+        } catch (e: DispatchException) {
+            dispatchException = e
         } catch (e: Throwable) {
             // This instead of runCatching to have nicer stacktrace and debug experience
             fatalException = e
         } finally {
             fatalException?.let { handleFatalException(it) }
+            dispatchException?.let { handleCoroutineException(delegate.context, it.cause) }
         }
```
Comment (dkhalanskyjb) [inline kotlinx-coroutines-core/common/src/internal/DispatchedTask.kt:114]: I just noticed: does this even need a `finally` now? I think this logic can just be moved to the `catch` blocks, can't it?

**Review by dkhalanskyjb — APPROVED** [review]
Good job!

File: kotlinx-coroutines-core/common/src/internal/DispatchedTask.kt [hunk 3]
```diff
@@ -205,3 +203,14 @@ internal inline fun DispatchedTask<*>.runUnconfinedEventLoop(
 internal inline fun Continuation<*>.resumeWithStackTrace(exception: Throwable) {
     resumeWith(Result.failure(recoverStackTrace(exception, this)))
 }
+
+/**
+ * This exception holds an exception raised in [CoroutineDispatcher.dispatch] method
```
Comment (qwwdfsad) [inline kotlinx-coroutines-core/common/src/internal/DispatchedTask.kt:208]: Please leave a comment that helps readers/maintainers to understand **why** it is here without looking into git blame and/or corresponding tests.
For example:

```suggestion
 * This exception holds an exception raised in [CoroutineDispatcher.dispatch] method.
 * When dispatcher methods fail unexpectedly, it is likely a user-induced programmatic bug,
 * such as calling `executor.close()` prematurely. To avoid reporting such exceptions as fatal errors,
 * we handle them with a separate code path. See also #4091.
```

**Review by qwwdfsad — APPROVED** [review]
Good job!

Please address/accept my comment and it is good to go.
