### PR TITLE
Fix stack overflow when calling asDeferred on a Future many times

### LINKED ISSUE #4156: Calling CompletionStage.asDeferred() on the same future many times causes stack overflows
**Describe the bug**

Given a shared `CompletableFuture` object `future`:

1. Attach other transformations on `future`, e.g. `val didRun = AtomicBoolean(); future.whenComplete { _, _ -> didRun.set(true) }`
2. Call `future.asDeferred()` many times. Generally, 10,000 times is sufficient to trigger the failure. The resulting `Deferred<*>` don't have to be used.
3. Complete `future` exceptionally, e.g. `future.completeExceptionally(RuntimeException())`.

**What happened? What should have happened instead?**

Actual: Some of the `Deferred<*>` results would not complete. Some of the extra transformations in (1) do not run.

The exception thrown from the completed `Deferred<*>` objects *may* contain a suppressed `StackOverflowError`. In testing, in most of the cases there is no indication that anything failed, and the StackOverflowError can be observed by setting a breakpoint inside CompletableFuture's internal machinery.

Expected: all the `Deferred<*>` results should complete exceptionally, and additional transforms attached in (1) should run.

**Why would you do this?**

The above condition can happen when you use an asynchronous cache, e.g. Caffeine.newBuilder()...buildAsync().

In such use cases, an underlying `CompletableFuture`-based cache would return a cached (and shared) `CompletableFuture` object, and code that is using the cache would call `CompletionStage.asDeferred()` to consume the cached future asynchronously.

In exceptional conditions, e.g. when the backend computation gated behind the cache slows to a crawl and then starts failing, the above described condition can happen - a single `CompletableFuture` is returned to a bunch of cache consumers while everybody is waiting for the computation to complete. If the incoming request rate is high enough, you can easily end up with 10,000 waiters on the same `CompletableFuture`.

Then, when backend computation finally fails, this bug is triggered.

Note: this bug is particular insidious because it is very hard to trigger normally, and when it does, caches can behave very unexpectedly.

In the case of Caffeine, because some transforms fail to run (1 above), Caffeine does not get notified that the `CompletableFuture` fail and keeps returning the same failed `CompletableFuture` to future callers.

**Why not CompletionStage.await()**

Because the `CompletableFuture` is shared between multiple callers. Using `CompletionStage.await()` will allow one caller's cancellation to break all other concurrent callers waiting on the same future.

**Provide a Reproducer**

This is a `*.main.kts`. Run with `kotlin <something>.main.kts <num calls>`.

```kotlin
@file:Repository("https://repo1.maven.org/maven2")
@file:DependsOn("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.1")

import kotlinx.coroutines.delay
import kotlinx.coroutines.future.asDeferred
import kotlinx.coroutines.runBlocking
import java.util.concurrent.CompletableFuture
import java.util.concurrent.atomic.AtomicBoolean
import kotlin.time.Duration.Companion.seconds

val numCalls = args[0].toInt()

val future = CompletableFuture<Unit>()

// Step 1
val didRun = AtomicBoolean(false)
future.whenComplete { _, _ -> didRun.set(true) }

// Step 2
val deferreds = (0 until numCalls).map { future.asDeferred() }

// Step 3
future.completeExceptionally(RuntimeException())

// There are no thread pool and executors involved above. All executions should complete on step 3.
runBlocking {
    // But just in case, wait a few seconds.
    delay(2.seconds)

    println("Expected additional transformation to run. Actual: ${didRun.get()}")
    println("Expected ${deferreds.size} Deferred<Unit> to complete exceptionally. Actual: ${deferreds.filter { it.isCompleted }.size}")
}
```

Versions:

* Mac OS X Sonoma 14.4.1, M3 Pro.
* java -version

```
openjdk version "21.0.3" 2024-04-16
OpenJDK Runtime Environment Homebrew (build 21.0.3)
OpenJDK 64-Bit Server VM Homebrew (build 21.0.3, mixed mode, sharing)
```

* kotlin -version: `Kotlin version 2.0.0-release-341 (JRE 21.0.3)`
* kotlinx-coroutines-core: 1.8.1 (above)

Results:

* `$ kotlin test.main.kts 100`: no bug

```
$ JAVA_HOME=/opt/homebrew/Cellar/openjdk@21/21.0.3/libexec/openjdk.jdk/Contents/Home kotlin test.main.kts 100
Expected additional transformation to run. Actual: true
Expected 100 Deferred<Unit> to complete exceptionally. Actual: 100
```
* `$ kotlin test.main.kts 10000`: bug, with various failure modes

```
$ JAVA_HOME=/opt/homebrew/Cellar/openjdk@21/21.0.3/libexec/openjdk.jdk/Contents/Home kotlin test.main.kts 10000
Expected additional transformation to run. Actual: true
Expected 10000 Deferred<Unit> to complete exceptionally. Actual: 8023
$ JAVA_HOME=/opt/homebrew/Cellar/openjdk@21/21.0.3/libexec/openjdk.jdk/Contents/Home kotlin test.main.kts 10000
Expected additional transformation to run. Actual: true
Expected 10000 Deferred<Unit> to complete exceptionally. Actual: 2970
$ JAVA_HOME=/opt/homebrew/Cellar/openjdk@21/21.0.3/libexec/openjdk.jdk/Contents/Home kotlin test.main.kts 10000
Expected additional transformation to run. Actual: true
Expected 10000 Deferred<Unit> to complete exceptionally. Actual: 9894
$ JAVA_HOME=/opt/homebrew/Cellar/openjdk@21/21.0.3/libexec/openjdk.jdk/Contents/Home kotlin test.main.kts 10000
Expected additional transformation to run. Actual: true
Expected 10000 Deferred<Unit> to complete exceptionally. Actual: 9995
$ JAVA_HOME=/opt/homebrew/Cellar/openjdk@21/21.0.3/libexec/openjdk.jdk/Contents/Home kotlin test.main.kts 10000
Expected additional transformation to run. Actual: false
Expected 10000 Deferred<Unit> to complete exceptionally. Actual: 8075
```

### PR DESCRIPTION
**Pull request by dkhalanskyjb**
Fixes #4156

### CODE REVIEW

File: kotlinx-coroutines-core/jdk8/src/future/Future.kt [hunk 1]
```diff
@@ -190,3 +190,18 @@ private class ContinuationHandler<T>(
...
+private class CancelFutureOnCompletion(
+    private val future: Future<*>
+) : JobNode() {
+    override fun invoke(cause: Throwable?) {
+        // Don't interrupt when cancelling future on completion, because no one is going to reset this
+        // interruption flag and it will cause spurious failures elsewhere.
+        // We do not cancel the future if it's already completed in some way,
+        // because `cancel` on a completed future won't change the state but is not guaranteed to behave well
+        // on reentrancy. See https://github.com/Kotlin/kotlinx.coroutines/issues/4156
+        if (cause != null && !future.isDone) future.cancel(false)
```
Comment (zuevmaxim) [inline kotlinx-coroutines-core/jdk8/src/future/Future.kt:203]: > but is not guaranteed to behave well on reentrancy
Can you please mention what exactly goes wrong? Something like `Reentrant cancellation of a future may cause repeated cancellation of it's dependants`

Comment (dkhalanskyjb) [reply kotlinx-coroutines-core/jdk8/src/future/Future.kt:203]: I don't think the documentation says anything specific, unfortunately, so what exactly goes wrong seems to be an implementation detail. In the issue linked, the problem was that `future.cancel` shared the job of calling the remaining `handle` callbacks, which called `future.cancel`, which shared the job, and so on recursively in the same thread.

File: kotlinx-coroutines-core/jvm/src/Future.kt [hunk 2]
```diff
@@ -5,42 +5,22 @@ package kotlinx.coroutines
...
-        // interruption flag and it will cause spurious failures elsewhere
-        if (cause != null) future.cancel(false)
-    }
-
-    override val onCancelling get() = false
-}
+    invokeOnCancellation(handler = PublicCancelFutureOnCancel(future))
 
-private class CancelFutureOnCancel(private val future: Future<*>) : CancelHandler {
+private class PublicCancelFutureOnCancel(private val future: Future<*>) : CancelHandler {
```
Comment (zuevmaxim) [inline kotlinx-coroutines-core/jvm/src/Future.kt:23]: The name is unclear to me. Should it be named `CancelFutureOnCancelWithCause`? Should we update `toString` by the way?

File: kotlinx-coroutines-core/jvm/src/Future.kt [hunk 3]
```diff
@@ -5,42 +5,22 @@ package kotlinx.coroutines
...
  * ```
  * invokeOnCancellation { if (it != null) future.cancel(false) }
  * ```
  */
+@Deprecated(
+    "This function does not do what its name implies: it will not cancel the future if just cancel() was called.",
+    level = DeprecationLevel.WARNING,
+    replaceWith = ReplaceWith("this.invokeOnCancellation { future.cancel(false) }")
+)
 public fun CancellableContinuation<*>.cancelFutureOnCancellation(future: Future<*>): Unit =
```
Comment (zuevmaxim) [inline kotlinx-coroutines-core/jvm/src/Future.kt:20]: There are no tests for this method. Should we introduce one? I will become clearer which cases this method does not cover

File: kotlinx-coroutines-core/jvm/src/Future.kt [hunk 4]
```diff
@@ -5,42 +5,22 @@ package kotlinx.coroutines
...
-
 /**
  * Cancels a specified [future] when this job is cancelled.
  * This is a shortcut for the following code with slightly more efficient implementation (one fewer object created).
  * ```
  * invokeOnCancellation { if (it != null) future.cancel(false) }
  * ```
  */
+@Deprecated(
+    "This function does not do what its name implies: it will not cancel the future if just cancel() was called.",
```
Comment (zuevmaxim) [inline kotlinx-coroutines-core/jvm/src/Future.kt:16]: > it will not cancel the future if just cancel() was called

Can you please specify the difference between the case when the method does work and does not work? For example, `The future will be cancelled only when the job is cancelled, but not the Continuation`

File: kotlinx-coroutines-core/jvm/src/Future.kt (hunk 2 above)
Comment (dkhalanskyjb) [reply kotlinx-coroutines-core/jvm/src/Future.kt:23]: I would call it `CancelFutureOnCancel`, but then, the class names would be in conflict, so I had to rename it.

File: kotlinx-coroutines-core/jvm/src/Executors.kt [hunk 5]
```diff
@@ -201,3 +200,12 @@ private class DisposableFutureHandle(private val future: Future<*>) : Disposable
     }
     override fun toString(): String = "DisposableFutureHandle[$future]"
 }
+
+private class CancelFutureOnCancel(private val future: Future<*>) : CancelHandler {
+    override fun invoke(cause: Throwable?) {
+        // Don't interrupt when cancelling future on completion, because no one is going to reset this
+        // interruption flag and it will cause spurious failures elsewhere
+        future.cancel(false)
```
[the remark this answers is not in the document]
Comment (dkhalanskyjb) [reply kotlinx-coroutines-core/jvm/src/Executors.kt:208]: I'm pretty sure we can't, but could you double-check it? Ensuring that the code is correct is typically shared equally between the author and the reviewer in this library, we tend to dive deep.

File: kotlinx-coroutines-core/jvm/src/Future.kt (hunk 4 above)
Comment (dkhalanskyjb) [inline kotlinx-coroutines-core/jvm/src/Future.kt:16]: @zuevmaxim,
```suggestion
    "This function does not do what its name implies: it will not cancel the future if the continuation was cancelled without a cause specified (e.g., via `cancel()` with no argument).",
```
?

File: kotlinx-coroutines-core/jvm/src/Future.kt (hunk 3 above)
Comment (dkhalanskyjb) [reply kotlinx-coroutines-core/jvm/src/Future.kt:20]: We could add some tests, but I don't think they would realistically help us catch regressions: the function is simple, and we're unlikely to ever change it again now that it's deprecated.

File: kotlinx-coroutines-core/jvm/src/Future.kt (hunk 4 above)
Comment (zuevmaxim) [reply kotlinx-coroutines-core/jvm/src/Future.kt:16]: Looks good

File: kotlinx-coroutines-core/jvm/src/Future.kt (hunk 2 above)
Comment (dkhalanskyjb) [reply kotlinx-coroutines-core/jvm/src/Future.kt]: Sure, `Deprecated` sounds good.

File: kotlinx-coroutines-core/jvm/src/Executors.kt (hunk 5 above)
[the remark this answers is not in the document]
Comment (zuevmaxim) [reply kotlinx-coroutines-core/jvm/src/Executors.kt:208]: I see no callbacks to be cancelled by the `future`, so I cannot come up with an example when there might be a problem

**Review by zuevmaxim — APPROVED** [review]

File: kotlinx-coroutines-core/jdk8/src/future/Future.kt [hunk 6]
```diff
@@ -190,3 +190,18 @@ private class ContinuationHandler<T>(
...
+    }
+
+    override val onCancelling get() = false
+}
```
Comment (qwwdfsad) [inline kotlinx-coroutines-core/jdk8/src/future/Future.kt:207]: AFAIR we consistently leave a trailing newline and there is an IDEA setting to do so

File: kotlinx-coroutines-core/jdk8/src/future/Future.kt [hunk 7]
```diff
@@ -190,3 +190,18 @@ private class ContinuationHandler<T>(
...
+    override fun invoke(cause: Throwable?) {
+        // Don't interrupt when cancelling future on completion, because no one is going to reset this
+        // interruption flag and it will cause spurious failures elsewhere.
+        // We do not cancel the future if it's already completed in some way,
+        // because `cancel` on a completed future won't change the state but is not guaranteed to behave well
+        // on reentrancy. See https://github.com/Kotlin/kotlinx.coroutines/issues/4156
+        if (cause != null && !future.isDone) future.cancel(false)
+    }
+
+    override val onCancelling get() = false
```
Comment (qwwdfsad) [inline kotlinx-coroutines-core/jdk8/src/future/Future.kt:206]: Code-style: properties before functions (though it seems we missed this during the original review)

File: kotlinx-coroutines-core/jvm/src/Future.kt [hunk 8]
```diff
@@ -5,46 +5,26 @@ package kotlinx.coroutines
...
-    invokeOnCompletion(handler = CancelFutureOnCompletion(future))
-
 /**
  * Cancels a specified [future] when this job is cancelled.
  * This is a shortcut for the following code with slightly more efficient implementation (one fewer object created).
  * ```
  * invokeOnCancellation { if (it != null) future.cancel(false) }
  * ```
  */
+@Deprecated(
```
Comment (qwwdfsad) [inline kotlinx-coroutines-core/jvm/src/Future.kt:15]: Please drop a comment since what version it's deprecated as we do in other places

**Review by qwwdfsad — APPROVED** [review]

File: kotlinx-coroutines-core/jdk8/src/future/Future.kt (hunk 7 above)
Comment (dkhalanskyjb) [reply kotlinx-coroutines-core/jdk8/src/future/Future.kt:206]: The point of this rule is unclear to me, but ok, changed this throughout the codebase.

File: kotlinx-coroutines-core/jvm/src/Future.kt (hunk 4 above)
Comment (lukellmann) [reply kotlinx-coroutines-core/jvm/src/Future.kt:17]: It seems like this change wasn't actually applied?
