### PR TITLE
Move trySendBlocking from jvm to concurrent source-set to make it ava…

### LINKED ISSUE #2983: Support trySendBlocking() Coroutines API in Kotlin/Native
NOTE: This is a mirror for the https://youtrack.jetbrains.com/issue/KT-49230, made to follow the [kotlinx.coroutines Contributing Guidelines](https://github.com/Kotlin/kotlinx.coroutines/blob/master/CONTRIBUTING.md#submitting-issues).
All the credits should go to @jeffdgr8(I hope I'm not mentioning the wrong person).

`trySendBlocking()` is [only available in Kotlin/JVM](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.channels/try-send-blocking.html). But the implementation doesn't seem to have any JVM-specific requirements. Copying the extension function to a KMM shared module compiles just fine, only warning about `InternalCoroutinesApi` usage in `ChannelResult`:

```
@Throws(InterruptedException::class)
public fun <E> SendChannel<E>.trySendBlocking(element: E): ChannelResult<Unit> {
    trySend(element).onSuccess { return ChannelResult.success(Unit) }
    return runBlocking {
        val r = runCatching { send(element) }
        if (r.isSuccess) ChannelResult.success(Unit)
        else ChannelResult.closed(r.exceptionOrNull())
    }
}
```

Can this function be added to support Kotlin/Native?

The deprecated `sendBlocking()` function that functions similarly is available, but can't be replaced with `trySendBlocking()` as it suggests.

### PR DESCRIPTION
**Pull request by qwwdfsad**
…ilable on K/N

Fixes #2983

### CODE REVIEW

File: kotlinx-coroutines-core/concurrent/test/channels/TrySendBlockingTest.kt [hunk 1]
```diff
@@ -1,17 +1,17 @@
 /*
- * Copyright 2016-2018 JetBrains s.r.o. Use of this source code is governed by the Apache 2.0 license.
+ * Copyright 2016-2021 JetBrains s.r.o. Use of this source code is governed by the Apache 2.0 license.
  */
 
-package kotlinx.coroutines.channels
+package channels
```
Comment (dkhalanskyjb) [inline kotlinx-coroutines-core/concurrent/test/channels/TrySendBlockingTest.kt:5]: Looks like the IDE messed up here.

**Review by dkhalanskyjb — APPROVED** [review]
