### PR TITLE
Fix race condition in pair select

### LINKED ISSUE #1561: SelectDeadlockLFStressTest.testLockFreedom fails with KNPE
See https://teamcity.jetbrains.com/viewLog.html?buildId=2544504&buildTypeId=KotlinTools_KotlinxCoroutines_NightlyStressWindows

Test `SelectDeadlockLFStressTest.testLockFreedom`:

```
kotlin.KotlinNullPointerException
	at kotlinx.coroutines.channels.AbstractSendChannel.offerSelectInternal(AbstractChannel.kt:68)
	at kotlinx.coroutines.channels.AbstractSendChannel.registerSelectSend(AbstractChannel.kt:400)
	at kotlinx.coroutines.channels.AbstractSendChannel.access$registerSelectSend(AbstractChannel.kt:18)
	at kotlinx.coroutines.channels.AbstractSendChannel$onSend$1.registerSelectClause2(AbstractChannel.kt:378)
	at kotlinx.coroutines.selects.SelectBuilderImpl.invoke(Select.kt:618)
	at kotlinx.coroutines.selects.SelectDeadlockLFStressTest$TestDef.sendClause(SelectDeadlockLFStressTest.kt:88)
	at kotlinx.coroutines.selects.SelectDeadlockLFStressTest$TestDef.access$sendClause(SelectDeadlockLFStressTest.kt:49)
	at kotlinx.coroutines.selects.SelectDeadlockLFStressTest$TestDef$$special$$inlined$apply$lambda$1.invoke(SelectDeadlockLFStressTest.kt:65)
	at kotlinx.coroutines.selects.SelectDeadlockLFStressTest$TestDef$$special$$inlined$apply$lambda$1.invoke(SelectDeadlockLFStressTest.kt:49)
	at kotlinx.coroutines.selects.SelectDeadlockLFStressTest$TestDef.doSendReceive(SelectDeadlockLFStressTest.kt:80)
	at kotlinx.coroutines.selects.SelectDeadlockLFStressTest$TestDef$test$1.invokeSuspend(SelectDeadlockLFStressTest.kt:74)
	at kotlinx.coroutines.selects.SelectDeadlockLFStressTest$TestDef$test$1.invoke(SelectDeadlockLFStressTest.kt)
	at kotlinx.atomicfu.LockFreedomTestEnvironment$TestThread.callOperation(LockFreedomTestEnvironment.kt:294)
	at kotlinx.atomicfu.LockFreedomTestEnvironment$TestThread.run(LockFreedomTestEnvironment.kt:223)
```

### PR DESCRIPTION
**Pull request by elizarov**
This bug was introduced by #1524. The crux of problem is that
TryOffer/PollDesc.onPrepare method is no longer allowed to update
fields in these classes (like "resumeToken" and "pollResult") after call
to tryResumeSend/Receive method, because the latter will complete
the ongoing atomic operation and helper method might find it complete
and try reading "resumeToken" which was not initialized yet.

This change removes "pollResult" field which was not really needed
("result.pollResult" field is used) and removes "resumeToken" by
exploiting the fact that current implementation of
CancellableContinuationImpl does not need a token anymore. However,
CancellableContinuation.tryResume/completeResume ABI is left intact,
because it is used by 3rd party code.

This fix lead to overall simplification of the code. A number of fields
and an auxiliary IdempotentTokenValue class are removed, tokens used to
indicate various results are consolidated, so that resume success
is now consistently indicated by a single RESUME_TOKEN symbol.

Fixes #1561

### CODE REVIEW

File: kotlinx-coroutines-core/common/src/channels/AbstractChannel.kt [hunk 1]
```diff
@@ -48,7 +48,8 @@ internal abstract class AbstractSendChannel<E> : SendChannel<E> {
             val receive = takeFirstReceiveOrPeekClosed() ?: return OFFER_FAILED
             val token = receive.tryResumeReceive(element, null)
```
Comment (qwwdfsad) [inline kotlinx-coroutines-core/common/src/channels/AbstractChannel.kt]: It looks like  `tryResumeReceive` can return either `Symbol` or null, it's time to update the signature
