### PR TITLE
Detect missing awaitClose calls in callbackFlow and close channel wit…

### LINKED ISSUE #1762: kotlin.coroutines.channels.awaitClose: JobCancellationException
The `awaitClose` function currently throws a `JobCancellationException` if the job was canceled before calling the function. 

I would have personally expected that the block passed to `awaitClose { }` gets executed without throwing this exception. 

Sample code:

```kotlin
internal fun SensorManager.consumeValuesAsFlow(
    sensor: Sensor,
    measureInterval: Duration = 20L with TimeUnit.MilliSeconds
): Flow<FloatArray> {
    return callbackFlow {
        val sensorEventListener = object : SensorEventListener {
            override fun onAccuracyChanged(sensor: Sensor?, accuracy: Int) = Unit
            override fun onSensorChanged(event: SensorEvent) {
                catch { offer(event.values) }
            }
        }

        registerListener(
            sensorEventListener,
            sensor,
            measureInterval[TimeUnit.MicroSeconds].toInt(),
            sensorHandler
        )
        try {
            awaitClose { unregisterListener(sensorEventListener) }
        } catch (t: Throwable) {
            Log.e("SensorManager", "consumeValuesAsFlow", t) // called with JobCancellationException
        }
    }
}
```

Coroutines version 1.3.3
Kotlin version 1.3.61

### LINKED ISSUE #1770: ClosedSendChannelException for callbackFlow
I'm trying to convert an Android CountDownTimer into emitting values via `callbackFlow` but it throws `ClosedSendChannelException: Channel was closed` when collecting the items. I can't really find a valid reason why this happens.

```kotlin
@ExperimentalCoroutinesApi
class TimerFlow private constructor(millisInFuture: Long, countDownInterval: Long) {

    private val tick: Flow<Long> = callbackFlow {

        object : CountDownTimer(millisInFuture, countDownInterval) {
            override fun onFinish() {
                offer(0L)
            }

            override fun onTick(millisUntilFinished: Long) {
                Log.i("TimerFlow","$millisUntilFinished")
                offer(millisUntilFinished)
            }
        }.start()
    }

    companion object {
        /**
         * Create a [Flow] that will be a countdown until a specified time in the future.
         *
         * @param millisInFuture The milliseconds in the future that this will countdown to.
         * @param countDownInterval The minimum amount of time between emissions.
         */
        @JvmStatic
        fun create(millisInFuture: Long, countDownInterval: Long) =
            TimerFlow(millisInFuture, countDownInterval).tick
    }
}
```
Is this a bug or am I missing something? I'm new to Coroutines.

### PR DESCRIPTION
**Pull request by qwwdfsad**
…h a proper diagnostic exception

Fixes #1762
Fixes #1770

### CODE REVIEW

File: kotlinx-coroutines-core/common/src/flow/Builders.kt [hunk 1]
```diff
@@ -315,3 +318,36 @@ private class ChannelFlowBuilder<T>(
...
+) : ChannelFlowBuilder<T>(block, context, capacity) {
+
+    private val collectCallback: suspend (ProducerScope<T>) -> Unit = {
+        collectTo(it)
+        /*
+         * We expect user either call `awaitClose` from within a block (then the channel is closed at this moment)
+         * or being closed/cancelled externally/manually. Otherwise "user forgot to call
+         * awaitClose and receives unhelpful ClosedSendChannelException exceptions" situation is detected.
+         */
+        if (it.isActive && !it.isClosedForSend) {
```
Comment (qwwdfsad) [inline kotlinx-coroutines-core/common/src/flow/Builders.kt]: Not sure about this very condition, will think it out for a while

File: kotlinx-coroutines-core/common/src/flow/Builders.kt [hunk 2]
```diff
@@ -287,21 +291,20 @@ public fun <T> channelFlow(@BuilderInference block: suspend ProducerScope<T>.()
...
  * ```
- *
- * This function is an alias for [channelFlow], it has a separate name to reflect
- * the intent of the usage (integration with a callback-based API) better.
  */
-@Suppress("NOTHING_TO_INLINE")
 @ExperimentalCoroutinesApi
-public inline fun <T> callbackFlow(@BuilderInference noinline block: suspend ProducerScope<T>.() -> Unit): Flow<T> =
-    channelFlow(block)
+public fun <T> callbackFlow(@BuilderInference block: suspend ProducerScope<T>.() -> Unit): Flow<T> = CallbackFlowBuilder(block)
```
Comment (qwwdfsad) [inline kotlinx-coroutines-core/common/src/flow/Builders.kt]: Let's consider replacing `offer` with `sendBlocking` in the sample

File: kotlinx-coroutines-core/common/src/flow/Builders.kt [hunk 3]
```diff
@@ -315,3 +318,36 @@ private class ChannelFlowBuilder<T>(
...
         "block[$block] -> ${super.toString()}"
 }
+
+private class CallbackFlowBuilder<T>(
+    private val block: suspend ProducerScope<T>.() -> Unit,
+    context: CoroutineContext = EmptyCoroutineContext,
+    capacity: Int = BUFFERED
+) : ChannelFlowBuilder<T>(block, context, capacity) {
+
+    private val collectCallback: suspend (ProducerScope<T>) -> Unit = {
```
Comment (elizarov) [inline kotlinx-coroutines-core/common/src/flow/Builders.kt]: It looks like you can simply make `collectTo` open and override it here. There will be no need to override `broadcastImpl` and `produceImpl`.

File: kotlinx-coroutines-core/common/src/flow/Builders.kt [hunk 4]
```diff
@@ -315,3 +318,36 @@ private class ChannelFlowBuilder<T>(
...
+         * or being closed/cancelled externally/manually. Otherwise "user forgot to call
+         * awaitClose and receives unhelpful ClosedSendChannelException exceptions" situation is detected.
+         */
+        if (it.isActive && !it.isClosedForSend) {
+            throw IllegalStateException(
+                """
+                    'awaitClose { yourCallbackOrListener.cancel() }' should be used in the end of callbackFlow block.
+                    Otherwise, a callback/listener may leak in case of cancellation external cancellation (e.g. by 'take(1)' or destroyed activity).
+                    For a more detailed explanation, please refer to callbackFlow KDoc. 
+            """.trimIndent())
```
Comment (elizarov) [inline kotlinx-coroutines-core/common/src/flow/Builders.kt]: Style nit: one more tab here. 

Also "KDoc" does not read nicely in prose. I'd replace it "... callbackFlow API documentation." And this can be much shorter sentence giving the same idea: "See callbackFlow API documentation for details".

File: kotlinx-coroutines-core/common/src/flow/Builders.kt (hunk 1 above)
Comment (elizarov) [reply kotlinx-coroutines-core/common/src/flow/Builders.kt]: It seems that `!it.isClosedForSend` should be enough.

File: kotlinx-coroutines-core/common/src/flow/Builders.kt (hunk 2 above)
Comment (elizarov) [reply kotlinx-coroutines-core/common/src/flow/Builders.kt]: Yes. It sounds like a great idea.

File: kotlinx-coroutines-core/common/src/flow/Builders.kt [hunk 5]
```diff
@@ -259,10 +259,14 @@ public fun <T> channelFlow(@BuilderInference block: suspend ProducerScope<T>.()
...
- * The [awaitClose] argument is called either when a flow consumer cancels the flow collection
- * or when a callback-based API invokes [SendChannel.close] manually.
+ * The resulting flow completes as soon as the code in the [block] completes.
+ * [awaitClose] should be used to keep the flow running, otherwise the channel will be closed immediately
+ * when block completes.
+ * [awaitClose] argument is called either when a flow consumer cancels the flow collection
+ * or when a callback-based API invokes [SendChannel.close] manually and is typically used
+ * to cleanup the resources after the completion, e.g. unregister a callback.
+ * Using [awaitClose] is mandatory in order to prevent memory leaks when the flow collection is cancelled,
+ * otherwise the callback may keep running even when the flow collector is already completed.
```
Comment (elizarov) [inline kotlinx-coroutines-core/common/src/flow/Builders.kt]: It should mention that `IllegalStateException` is thrown in cases when block returns but the channel was not closed yet.

File: kotlinx-coroutines-core/common/src/flow/internal/ChannelFlow.kt [hunk 6]
```diff
@@ -27,6 +27,14 @@ public abstract class ChannelFlow<T>(
     // buffer capacity between upstream and downstream context
     @JvmField val capacity: Int
 ) : Flow<T> {
+
+    // shared code to create a suspend lambda from collectTo function in one place
+    internal val collectToFun: suspend (ProducerScope<T>) -> Unit
+        get() = { collectTo(it) }
+
+    protected val produceCapacity: Int
```
Comment (elizarov) [inline kotlinx-coroutines-core/common/src/flow/internal/ChannelFlow.kt]: This can be private as it was before.

File: kotlinx-coroutines-core/common/src/flow/Builders.kt [hunk 7]
```diff
@@ -277,31 +283,34 @@ public fun <T> channelFlow(@BuilderInference block: suspend ProducerScope<T>.()
...
  *         }
  *         override fun onCompleted() = channel.close()
  *     }
  *     api.register(callback)
- *     // Suspend until either onCompleted or external cancellation are invoked
+ *     /*
+ *      * Suspends until either 'onCompleted' from the callback is invoked
+ *      * or flow collector is cancelled (e.g. by 'take(1)' or because a collector's activity was destroyed).
+ *      * In both cases, callback will be properly unregistered.
+ *      */
```
Comment (elizarov) [inline kotlinx-coroutines-core/common/src/flow/Builders.kt]: A few notes on this comment:
* "Suspends until either 'onCompleted' from the callback is invoked" -> should mention `onApiError`, too
* "or because a collector's activity was destroyed" looks out-of-place here -> replace with "collector's coroutine was cancelled"

File: kotlinx-coroutines-core/common/src/flow/Builders.kt [hunk 8]
```diff
@@ -315,3 +324,31 @@ private class ChannelFlowBuilder<T>(
...
+        /*
+         * We expect user either call `awaitClose` from within a block (then the channel is closed at this moment)
+         * or being closed/cancelled externally/manually. Otherwise "user forgot to call
+         * awaitClose and receives unhelpful ClosedSendChannelException exceptions" situation is detected.
+         */
+        if (!scope.isClosedForSend) {
+            throw IllegalStateException(
+                """
+                    'awaitClose { yourCallbackOrListener.cancel() }' should be used in the end of callbackFlow block.
+                    Otherwise, a callback/listener may leak in case of cancellation external cancellation (e.g. by 'take(1)' or destroyed activity).
```
Comment (elizarov) [inline kotlinx-coroutines-core/common/src/flow/Builders.kt]: " ... in case of cancellation external cancellation (e.g. by 'take(1)' or destroyed activity)." -> "cancellation" is repeated here; "destroyed activity" is out of place. I'd actually remove the explanation in the parenthesis altogether. A prompt to read the API docs (where it is all explained in detail) should be enough.

**Comment by mhernand40** [comment]
Any chance this would end up fixing https://github.com/tfcporciuncula/flow-preferences/issues/1? Thank you.
