### PR TITLE
Breaking change: Experimental Flow.onCompletion contract for cause

### LINKED ISSUE #1693: Flow: Operator for action on successful completion
According to the [doc](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/on-completion.html), the `onCompletion()` "operator is transparent to exceptions that occur in downstream flow and does not observe exceptions that are thrown to cancel the flow".

If I want to do something only when the flow is "successfully completed" (i.e. no exception, not cancelled), how can I do that? Thanks.

It can be reproduced with the following code:
```
import kotlinx.coroutines.*
import kotlinx.coroutines.flow.*

fun foo(): Flow<Int> = flow {
    var i = 0
    while (true) {
        emit(i++)
        delay(100)
    }
}

suspend fun main() {
    val job = GlobalScope.launch {
        foo().onEach { println("onEach: $it")}
            .onCompletion {
                println("onCompletion: $it")
            }
            .collect()
    }
    
    delay(500)
    println("after delay()")
    job.cancel()
    
    delay(100)
    println("after second delay()")
}
```

### PR DESCRIPTION
**Pull request by elizarov**
Flow.onCompletion now reports all failures and cancellation in its cause just like invokeOnCompletion. A null cause is reported if and only if flow had completed successfully (no failure, no cancellation). Emission of additional elements after the end of the flow is only possible from inside of onCompletion block in case of successful completion.

Also fixed a bug where onCompletion implementation was trying to add exception to its own list of suppressed exceptions, which is not allowed.

Fixes #1693

### CODE REVIEW

File: kotlinx-coroutines-core/common/src/flow/operators/Emitters.kt [hunk 1]
```diff
@@ -101,48 +101,55 @@ public fun <T> Flow<T>.onStart(
...
+ * ```
+ * myFlow
+ *     .onEach { println(it) }
+ *     .onCompletion { if (it == null) println("Completed successfully") }
  *     .collect()
  * ```
  *
  * The receiver of the [action] is [FlowCollector] and this operator can be used to emit additional
- * elements at the end of the collection. For example:
+ * elements at the end if it had completed successfully. For example:
```
Comment (qwwdfsad) [inline kotlinx-coroutines-core/common/src/flow/operators/Emitters.kt]: Just `completed`
