### PR TITLE
Clarify the behavior of CoroutineExceptionHandler

### LINKED ISSUE #1157: CoroutineExceptionHandler not called in top-most parent-scope.
I have this example code-snipper:
```
val xHandlerParent = CoroutineExceptionHandler { c, e ->
    println("Parent Handled Crash")
}

val xHandlerLeaf = CoroutineExceptionHandler { c, e ->
    println("Leaf Handled Crash")
}

fun test1() {
    // Exception throw up the call-stack. Expected
    CoroutineScope(Job()).launch {
        delay(1000)
        throw Exception("Some Exception 1")
    }

    Thread.sleep(2000)
}

fun test2() {
    // Exception handled by xHandlerParent: Expected
    CoroutineScope(xHandlerParent).launch {
        delay(1000)
        throw Exception("Some Exception 1")
    }

    Thread.sleep(2000)
}

fun test3() {
    // Exception handled by xHandlerLeaf: Expected?
    // Yes, since there is a top scope with a CoroutineExceptionHandler.
    // No,  since the top-most scope does not have CoroutineExceptionHandler.
    CoroutineScope(Job()).launch(xHandlerLeaf) {
        delay(1000)
        throw Exception("Some Exception 1")
    }

    Thread.sleep(2000)
}

fun test4() {
    // Exception handled by xHandlerLeaf. Unexpected.
    // Shouldn't it be handled by xHandlerParent instead?
    CoroutineScope(xHandlerParent).launch(xHandlerLeaf) {
        delay(1000)
        throw Exception("Some Exception 1")
    }

    Thread.sleep(2000)
}

fun test5() {
    // Exception handled by xHandlerParent: Expected
    CoroutineScope(xHandlerParent).launch {
        withContext(xHandlerLeaf) {
            delay(1000)
            throw Exception("Some Exception 1")
        }
    }

    Thread.sleep(2000)
}

fun test6() {
    // Exception handled by xHandlerParent: Expected?
    // Yes, since there is a top scope with a CoroutineExceptionHandler.
    // No,  since the top-most scope does not have CoroutineExceptionHandler.
    CoroutineScope(Job()).launch(xHandlerParent) {
        launch(xHandlerLeaf) {
            delay(1000)
            throw Exception("Some Exception 1")
        }
    }

    Thread.sleep(2000)
}

fun test7() {
    // Exception thrown up the call-stack. Expected?
    // Yes, since the top-most scope does not have CoroutineExceptionHandler.
    // No, since there is a top scope with a CoroutineExceptionHandler.
    CoroutineScope(Job()).launch {
        withContext(xHandlerLeaf) {
            delay(1000)
            throw Exception("Some Exception 1")
        }
    }

    Thread.sleep(2000)
}
```

My questions are:
- Is the top-most scope always used and if it has `CoroutineExceptionHandler`, it will be used, otherwise, the exception is thrown up the call-stack?
- Or is the top scope that has a `CoroutineExceptionHandler` used instead? Only if no such top scope can be found, the exception is thrown up the call-stack.
- Regardless of the answer to the previous question, why does the example of `test4()` not use the `xHandlerParent`, since that is the `CoroutineExceptionHandler` of the top and top-most scope?

### LINKED ISSUE #4504: Documentation needs adjustments: states async cannot cause uncaught exceptions but async can if fails before it is awaited.
The above states that:  `async` cannot create uncaught exceptions.

However: IF `async` throws an exception BEFORE we called `await` on the deferred object, THEN uncaught exception happens BUT `CoroutineExceptionHandler` does not appear to be invoked. 

#### Code self contained

```
package com.glassthought.sandbox

import kotlinx.coroutines.*
import java.time.Instant
import kotlin.time.Duration
import kotlin.time.Duration.Companion.milliseconds
import kotlin.time.Duration.Companion.seconds


fun main(): Unit {
  val coroutineExceptionHandler = CoroutineExceptionHandler { _, ex ->
    runBlocking(CoroutineName("CoroutineExceptionHandler")) {
      printlnWithTime("Caught exception in CoroutineExceptionHandler: ${ex::class.simpleName} with message=[${ex.message}].")
    }
  }

  val mainJob = Job()
  val scope = CoroutineScope(mainJob + coroutineExceptionHandler)

  scope.launch(CoroutineName("SpawnedFromMain")) {
    actionWithMsg("foo", { foo(scope) })
  }

  runBlocking {
    actionWithMsg("mainJob.join()", { mainJob.join() })
  }
}

private suspend fun foo(scope: CoroutineScope) {
  val deferred = scope.async(CoroutineName("async-1")) {
    actionWithMsg("throw-exception", {
      throw MyRuntimeException.create("exception-from-async-before-it-got-to-await")
    }, delayDuration = 500.milliseconds)
  }

  printlnWithTime("Just launched co-routines.")
  actionWithMsg(
    "deferred.await()",
    {
      deferred.await()
    },
    delayDuration = 1.seconds
  )
}

suspend fun <T> actionWithMsg(
  actionName: String,
  action: suspend () -> T,
  delayDuration: Duration = Duration.ZERO
): T {
  val hasDelay = delayDuration > Duration.ZERO
  if (hasDelay) {
    printlnWithTime("action=[$actionName] is being delayed for=[${delayDuration.inWholeMilliseconds} ms] before starting.")

    delay(delayDuration)
  }
  printlnWithTime("action=[$actionName] is starting.")

  var result: T


  try {
    result = action()
  } catch (exc: Exception) {
    // We are going to rethrow all exceptions, so CancellationException will also be rethrown.
    // Therefore, we respect: [Cooperative Cancellation](http://www.glassthought.com/notes/3ha01u9931je002miy86vdo)
    if (exc is CancellationException) {
      printlnWithTime("Cancellation Exception - rethrowing.")
    } else {
      printlnWithTime("Finished action=[$actionName], it THREW exception of type=[${exc::class.simpleName}] we are rethrowing it.")
    }
    throw exc
  }

  printlnWithTime("Finished action=[$actionName].")

  return result
}

class MyRuntimeException private constructor(msg: String) : RuntimeException(msg) {
  companion object {
    suspend fun create(msg: String): MyRuntimeException {
      val exc = MyRuntimeException(msg)

      printlnWithTime("throwing exception=[${exc::class.simpleName}] with msg=[${msg}]")

      return exc
    }
  }
}

fun printlnWithTime(msg: String) {
  println("[${Instant.now()}]: " + msg)
}
```
#### Original Code
```kotlin
package com.glassthought.sandbox

import com.glassthought.sandbox.util.out.impl.out
import kotlinx.coroutines.*
import kotlin.time.Duration.Companion.milliseconds
import kotlin.time.Duration.Companion.seconds


fun main(): Unit {
  val coroutineExceptionHandler = CoroutineExceptionHandler { _, ex ->
    runBlocking(CoroutineName("CoroutineExceptionHandler")) {
      out.error("Caught exception in CoroutineExceptionHandler: ${ex::class.simpleName} with message=[${ex.message}].")
    }
  }

  val mainJob = Job()
  val scope = CoroutineScope(mainJob + coroutineExceptionHandler)

  scope.launch(CoroutineName("SpawnedFromMain")) {
    out.actionWithMsg("foo", { foo(scope) })
  }
  
  runBlocking {
    out.actionWithMsg("mainJob.join()", { mainJob.join() })
  }
}

private suspend fun foo(scope: CoroutineScope) {
  val deferred = scope.async(CoroutineName("async-1")) {
    out.actionWithMsg("throw-exception", {
      throw MyRuntimeException.create("exception-from-async-before-it-got-to-await", out)
    }, delayDuration = 500.milliseconds)
  }

  out.info("Just launched co-routines.")
  out.actionWithMsg(
    "deferred.await()",
    {
      deferred.await()
    },
    delayDuration = 1.seconds
  )
}
```

#### Recorded output of command:
```txt
Picked up JAVA_TOOL_OPTIONS: -Dkotlinx.coroutines.debug
Picked up JAVA_TOOL_OPTIONS: -Dkotlinx.coroutines.debug
[INFO][elapsed:   18ms][①][coroutname:@SpawnedFromMain#1] [->] action=[foo] is starting.
[INFO][elapsed:   18ms][⓶][coroutname:@coroutine#2] [->] action=[mainJob.join()] is starting.
[INFO][elapsed:   31ms][①][coroutname:@SpawnedFromMain#1]    Just launched co-routines.
[INFO][elapsed:   35ms][①][coroutname:@SpawnedFromMain#1]    [🐢] action=[deferred.await()] is being delayed for=[1000 ms] before starting.
[INFO][elapsed:   35ms][⓷][coroutname:@async-1#3] [🐢] action=[throw-exception] is being delayed for=[500 ms] before starting.
[INFO][elapsed:  535ms][⓷][coroutname:@async-1#3] [->] action=[throw-exception] is starting.
[WARN][elapsed:  557ms][⓷][coroutname:@async-1#3]    💥 throwing exception=[MyRuntimeException] with msg=[exception-from-async-before-it-got-to-await]
[WARN][elapsed:  557ms][⓷][coroutname:@async-1#3] [<-][💥] Finished action=[throw-exception], it THREW exception of type=[MyRuntimeException] we are rethrowing it.
[INFO][elapsed:  568ms][①][coroutname:@SpawnedFromMain#1] [<-][🫡] Cancellation Exception - rethrowing.
[INFO][elapsed:  569ms][⓶][coroutname:@coroutine#2] [<-] Finished action=[mainJob.join()].
```

#### Output colored per co-routine:
Image

### PR DESCRIPTION
**Pull request by dkhalanskyjb**
The existing documentation didn't specify in detail which exceptions were considered unpropagated,
and was also using the confusing "uncaught" wording.

Fixes #1157
Fixes #4504

### CODE REVIEW

File: kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt [hunk 1]
```diff
@@ -50,29 +50,154 @@ public inline fun CoroutineExceptionHandler(crossinline handler: (CoroutineConte
     }
 
 /**
- * An optional element in the coroutine context to handle **uncaught** exceptions.
+ * An optional element in the [CoroutineContext] to handle coroutine exceptions without a clear propagation path.
```
Comment (murfel) [inline kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt:62]: You've somewhat created a bunch of new terms to replace a single old one. It used to be _uncaught exceptions_, now it is _unpropagated exceptions_, and it is introduced indirectly through mentions of a mix of wordings:
* clear propagation paths
* exception propagation paths
* clear exception propagation paths
* propagation channels

To mean "means of handling exceptions which come after try-catch but before CoroutineExceptionHandler".

It definitely needs to be standardised. I suggest either "exception propagation paths" or "propagation channels", or something else. (Drop the "clear". It makes it sound informal, but we do want to signal that it is a formal term).

No strong opinion on which term to use, as both have downsides and I cannot come up with a better one. "exception propagation paths" are too lengthy and "propagation channels" misleadingly mention channels.

File: kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt [hunk 2]
```diff
@@ -50,29 +50,154 @@ public inline fun CoroutineExceptionHandler(crossinline handler: (CoroutineConte
...
  *
- * Normally, uncaught exceptions can only result from _root_ coroutines created using the [launch][CoroutineScope.launch] builder.
- * All _children_ coroutines (coroutines created in the context of another [Job]) delegate handling of their
- * exceptions to their parent coroutine, which also delegates to the parent, and so on until the root,
- * so the `CoroutineExceptionHandler` installed in their context is never used.
- * Coroutines running with [SupervisorJob] do not propagate exceptions to their parent and are treated like root coroutines.
- * A coroutine that was created using [async][CoroutineScope.async] always catches all its exceptions and represents them
- * in the resulting [Deferred] object, so it cannot result in uncaught exceptions.
+ * `kotlinx.coroutines` ensures that every [exception][Throwable] thrown in a coroutine is handled by some code instead
```
Comment (murfel) [inline kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt]: It feels somehow off to refer to the library name. I like how you refer to the magic _coroutine machinery_ below. Use that?

File: kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt [hunk 3]
```diff
@@ -50,29 +50,154 @@ public inline fun CoroutineExceptionHandler(crossinline handler: (CoroutineConte
...
+ * of being forgotten about.
+ * This helps failures not to go unnoticed, with the program silently entering an incorrect state.
```
Comment (murfel) [inline kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt]: Too verbose.
> ensures that every exception thrown in a coroutine is handled.

File: kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt [hunk 4]
```diff
@@ -50,29 +50,154 @@ public inline fun CoroutineExceptionHandler(crossinline handler: (CoroutineConte
...
  *
```
Comment (murfel) [inline kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt:66]: I'd also add an overview of the upcoming exception handling hierarchy:
1. try-catch
2. "exception propagation paths"
3. CoroutineExceptionHandler
4. final resort

The #2 could also benefit from a brief overview (lexically scoped, parent, return value (deferred)).

It would be better to put it in a very brief listicle rather than complete sentences and acknowledge that it doesn't provide the full information yet.

File: kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt [hunk 5]
```diff
@@ -50,29 +50,154 @@ public inline fun CoroutineExceptionHandler(crossinline handler: (CoroutineConte
...
- * ### Handling coroutine exceptions
+ * In most scenarios, a clear exception propagation path allows processing failures in coroutines: for example,
+ * a [coroutineScope] call can rethrow the exception to the caller,
+ * and failing coroutines typically [cancel][Job.cancel] their [parent][Job.parent] coroutines.
+ * See "Propagation channels recognized by `kotlinx.coroutines`" below for an enumeration of ways an exception in a
```
Comment (murfel) [inline kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt]: I appreciate that you want to cut to the chase as early as possible. Consider doing it even sooner with a tiny example after the first sentence (for those who are familiar but only want to lookup the syntax of adding a CEH), and then you'll be able to keep the narrative linear without forward referencing. Currently it reads, "if your coroutines don't have something vague, for example in this case, use CoroutineExceptionHandler".

You already mention the `supervisorScope` example twice: once in this section, and once at the end of the Propagation channels section.

If you add a quick `supervisorScope` example at the top and have a linear story, it will only appear once later, on the border of the Propagation Channels and CEH sections.

File: kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt [hunk 6]
```diff
@@ -50,29 +50,154 @@ public inline fun CoroutineExceptionHandler(crossinline handler: (CoroutineConte
...
+ *             This is not an unpropagated exception,
+ *             since it gets caught.
+ *         """)
+ *     } catch (_: IllegalStateException) {
+ *         println("Caught an exception")
+ *     }
+ * }
+ * ```
+ *
+ * Exceptions in lexically scoped coroutines are always propagated by being rethrown to the caller:
```
Comment (murfel) [inline kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt]: Can we by any chance add a hyperlink to anywhere where "lexically scoped" is defined?

File: kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt [hunk 7]
```diff
@@ -81,19 +206,63 @@ public inline fun CoroutineExceptionHandler(crossinline handler: (CoroutineConte
  * }
```
Comment (murfel) [inline kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt:218]: rethrow CancellationException

**Review by murfel — CHANGES_REQUESTED** [review]

File: kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt (hunk 5 above)
Comment (dkhalanskyjb) [reply kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt]: I attempted this and didn't like the result:
```kotlin
  * There are scenarios when there is no clear propagation path that `kotlinx.coroutines` can take to propagate an
  * exception. Example:
  *
  * ```
  * supervisorScope {
  *     launch { error("Failure") }
  * }
  * ```
  *
  * Here, the coroutine created by `launch` fails with the exception `"Failure"`.
  * If instead of [supervisorScope], [coroutineScope] were used, the exception would be propagated to the caller of
  * [coroutineScope]. First, the failed [launch] would call [Job.cancel] on the [coroutineScope], which would lead
  * to [coroutineScope] failing. Then, since [coroutineScope] returns its result to the caller, the exception would
  * be rethrown. `kotlinx.coroutines` considers this a propagation path.
  *
  * However, [supervisorScope] does not react to exceptions from its children, as opposed to [coroutineScope],
  * which means [Job.cancel] would not be called.
  *
  * In such cases, a [CoroutineExceptionHandler] should be used to process the exceptions:
  *
  * ```
  * withContext(CoroutineExceptionHandler { ctx, ex ->
  *     println("Exception $ex thrown from coroutine context $ctx")
  * }) {
  *     supervisorScope {
  *         launch { error("Failure") }
  *     }
  * }
  * ```
  *
  * In most scenarios, a clear exception propagation path allows processing failures in coroutines.
  * Code should normally be structured in a way that ensures the existence of exception propagation paths.
  * See "Propagation paths recognized by `kotlinx.coroutines`" below.
```
* The minor role of `CoroutineExceptionHandler` is not as prominent. "There are scenarios" does not give any indication that these scenarios are unusual, and I didn't find a more natural way of expressing this thought than just starting with the idea that `CoroutineExceptionHandler` is unnecessary in most cases.
* The logic is backwards: to explain why `supervisorScope { launch }` fails to meet the propagation path criteria, we have to introduce them afterwards, overloading the reader.

File: kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt (hunk 3 above)
Comment (dkhalanskyjb) [reply kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt]: Your proposed formulation misses an important nuance. By "handling", people often mean "*appropriately* reacting to", but `kotlinx.coroutines` can't do that. The appropriate action heavily depends on the use case. The extra wording here weakens the "handling" to "*somehow* reacting to". I don't think rewording this would help with verbosity, either, as this is in any case an important point that shouldn't stay implicit.

File: kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt (hunk 2 above)
Comment (dkhalanskyjb) [reply kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt]: The other usages of "coroutine machinery" (`git grep machinery`) indicate that it's the sum of `JobSupport`, `CancellableContinuationImpl`, etc.—a specific implementation of how coroutines interact, suspend, resume, etc. With that in mind, using "the coroutines machinery" here becomes misleading, as not only the low-level implementation of corouttines themselves follows this principle, but other parts of the library as well: `git grep handleCoroutineException`. The mention of `kotlinx.coroutines` here is intended to evoke the feeling of it being a general guiding principle for our APIs.

File: kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt (hunk 1 above)
Comment (dkhalanskyjb) [reply kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt:62]: "Propagation channels" is a nice catch! We have already discussed it once already under the PR with the structured concurrency documentation, and you raised a valuable point that "channel" is a specific term in concurrent programming. Removed all mentions of channels to prevent confusion.

> Drop the "clear". It makes it sound informal, but we do want to signal that it is a formal term

I don't think that we do at that point. "Clear" only occurs in the first section, whose goal is to provide a high-level intuition of the forces at play. In my view, it is perfectly fine to add extra adjectives/verbosity to aid intuition there. The goal of "clear" is to contrast the propagation paths discussed here with those implied by the business logic. Generally, before it's clear that "propagation paths" is a precise characterization and not just a description of circumstances, "coroutine exceptions without a propagation path" looks meaningless to me, and "coroutine exceptions that `kotlinx.coroutines` can not propagate to where the client code can be expected to observe and react to them" feels detailed enough to obscure the high-level idea.

File: kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt (hunk 4 above)
Comment (dkhalanskyjb) [reply kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt:66]: I'm wary that this would postpone explaining the general idea of what a `CoroutineExceptionHandler` is and when it's needed. Would be a waste to have a reader go through this list, figure out the exception propagation paths, and then realize that hey, their code is already completely idiomatic, there is no need to be concerned about such low-level details.

File: kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt (hunk 3 above)
Comment (murfel) [reply kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt]: I only took a prefix of your text. 

"instead of being forgotten about" and "This helps failures not to go unnoticed, with the program silently entering an incorrect state" feel like general discussion on why it's important to handle exceptions, not relaxation of the meaning of "handle".

Let's relax the meaning of "handle" into "reacted to" and also shorten the discussion (which is useful to mention on its own merit)

> `kotlinx.coroutines` ensures that every [exception][Throwable] thrown in a coroutine is reacted to by some code. This helps to draw attention to failures and notice when the program enters an incorrect state.

File: kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt (hunk 7 above)
Comment (murfel) [reply kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt:218]: If this is our idiomatic rethrowing, shall we use the same in our tutorial? Instead of `throw e`.

https://kotlinlang.org/docs/cancellation-and-timeouts.html#cancel-coroutines

File: kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt (hunk 5 above)
Comment (murfel) [reply kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt]: What about this? This uses "exception propagation paths" as a level of abstraction. Even though you don't know if this applies to you or not if you don't know what is "exception propagation paths", you get the big picture, and now you only need to learn if your current situation has a propagation paths already or not.

```
 * An optional element in the [CoroutineContext] to handle coroutine exceptions without a clear propagation path.
 *
 * Code should normally be structured in a way that ensures the existence 
 * of exception propagation paths.
 * For example, a [coroutineScope] call will rethrow an exception to the caller.
 * In rare scenarios when there is no exception propagation path,
 * a [CoroutineExceptionHandler] should be used to process exceptions.
 * In such cases, not using a [CoroutineExceptionHandler] is considered a programming error
 * and will invoke _last-resort exception handling_ which may crash the program.
 *
 * Here, the coroutine created by `launch` fails with the exception `"Failure"`
 * but [supervisorScope] does not react to exceptions from its children,
 * as opposed to [coroutineScope].
 *
 * ```
 * supervisorScope {
 *     launch { error("Failure") }
 * }
 * ```
 *
 * In such cases, a [CoroutineExceptionHandler] should be used to process the exceptions:
 *
 * ```
 * withContext(CoroutineExceptionHandler { ctx, ex ->
 *     println("Exception $ex thrown from coroutine context $ctx")
 * }) {
 *     supervisorScope {
 *         launch { error("Failure") }
 *     }
 * }
 * ```
 *
 * Read below on general philosophy, exception propagation paths, and _last-resort exception handling_.
 ```

Comment (murfel) [reply kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt]: In fact, it is not re-ordering of sections, it is a replacement for the intro section. The current intro section is hard to digest and get a big picture exactly because it already dives into details of a propagation path for coroutineScope + launch.

I'd say it's more important to give a cleaner big picture without one chunk ("exception propagation paths") then to give a harder-to-digest big picture with a vague idea of that chunk.

File: kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt (hunk 3 above)
Comment (dkhalanskyjb) [reply kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt]: The problem isn't the exception hygiene and error handling best practices, though. It's that asynchronous computations don't have an inherent exception propagation path, the way exceptions can bubble up to the `public static void main` and crash the program if you leave them untouched on their way up.

A more disciplined, math-book-like way to structure this piece of documentation would be to extract a separate section called something like "Error handling in concurrent code" and explain in general terms that for queue-based-executor-based concurrency, some exceptions will inherently have nowhere to go. I was hoping to avoid this heavy methodical approach in favor of a specific example of an "intuitively" bad behavior the existence of `CoroutineExceptionHandler` aims to address.

> Let's relax the meaning of "handle" into "reacted to"

We can't get rid of "handling" as a word entirely, since the interface is called `CoroutineExceptionHandler`. Might as well lean into it.

File: kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt (hunk 5 above)
Comment (dkhalanskyjb) [reply kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt]: The idea behind the `coroutineScope { launch { } }` detour is that the reader will look at it, recognize their code is not affected by any problems `CoroutineExceptionHandler` is designed to solve, and move on.

In your proposed alternative, we risk involving the reader that may not at all be interested in the contents—there is no "happy fast path".

```
* Code should normally be structured in a way that ensures the existence of exception propagation paths.
* In rare scenarios when there is no exception propagation path,
* a [CoroutineExceptionHandler] should be used to process exceptions.
```

The reaction I expect: "Okay, so it turns out, I must structure my code somehow. I guess I'll need to go figure out how to do that. Why am I only learning about this here? The coroutine tutorial didn't mention anything about needing to structure my code in some specific way" Then, the reader ends up in the technical deep-dive into the propagation paths, which, ideally, they shouldn't even need. It takes effort to learn the details and then recognize that unknowingly, you've already been doing everything right.

Comment (murfel) [reply kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt]: We can plug the `coroutineScope` back in:

```
 * An optional element in the [CoroutineContext] to handle coroutine exceptions 
 * without a clear propagation path.
 *
 * Code should normally be structured in a way that ensures the existence 
 * of exception propagation paths.
 * For example, a [coroutineScope] call will rethrow an exception to the caller.
```

Edited my suggested snippet above to include this, and some other minor wordings.

The difference with the committed version is frontloading the form of the text.

File: kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt (hunk 3 above)
Comment (murfel) [reply kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt]: You want to communicate (a 10% of):
1. In an async framework, exception propagation is not as straightforward as in a regular program. 
2. We can't truly **handle** exceptions without a propagation path, we can just react to them.

Just FYI, this quote does neither for me, doesn't even clue at these.
> ... instead of being forgotten about. This helps failures not to go unnoticed, with the program silently entering an incorrect state.

I understand how you went from 1+2 to this by simplifying, but this turned out to be a very erasing transformation.

And for what it is now, it looks just like a general discussion on exceptions.

Comment (dkhalanskyjb) [reply kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt]: 1. I don't want this couple of sentences to communicate that, no. The purpose is to lead up to it. The example of `supervisorScope` and `launch` is supposed to demonstrate the problem in specific terms.
2. Likewise, I don't intend to make this contradiction. The idea is to clarify what exactly `kotlinx.coroutines` seeks to do, and that is that exceptions don't get completely forgotten about.

The ideas that asynchronously thrown exceptions are problematic + not being able to fully handle exceptions are the underlying reasons for this piece of text, not its message.

File: kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt (hunk 5 above)
Comment (dkhalanskyjb) [reply kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt]: The outline you provide already reads too abstract to me, I'm wary of losing the reader in these general words. Attempting to pad out the outline to a full text results in a yet longer span of technical information without anything to ground the reader using the concept they may be familiar with.

File: kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt (hunk 7 above)
Comment (dkhalanskyjb) [reply kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt:218]: It's complicated: https://github.com/Kotlin/kotlinx.coroutines/issues/1814#issuecomment-1943224856
In the specific example in the tutorial, anything goes; here, `ensureActive()` is needed; in general, there is no one-size-fits-all solution.

File: kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt [hunk 8]
```diff
@@ -40,70 +40,257 @@ internal fun handlerException(originalException: Throwable, thrownException: Thr
...
     }
 
 /**
- * An optional element in the coroutine context to handle **uncaught** exceptions.
+ * An optional element in the [CoroutineContext] to handle coroutine exceptions without a clear propagation path.
+ *
+ * This interface is part of the overall strategy through which `kotlinx.coroutines` ensures [exceptions][Throwable]
+ * don't go unnoticed.
+ *
+ * In most scenarios, a clear exception propagation path for processing failures in coroutines does exist.
```
Comment (murfel) [inline kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt]: "there exists"

File: kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt [hunk 9]
```diff
@@ -40,70 +40,257 @@ internal fun handlerException(originalException: Throwable, thrownException: Thr
...
+ * The only exceptions that need to be propagated at all are those with which coroutines finish.
+ * If an exception is handled via a `try`/`catch` block inside the coroutine itself,
+ * the coroutine machinery will not even learn about it:
+ *
+ * ```
+ * launch {
+ *     try {
+ *         throw IllegalStateException("""
+ *             This is not an unpropagated exception,
+ *             since it gets caught.
```
Comment (murfel) [inline kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt]: Too many negations make it hard to parse. Maybe something like "This exception does not need to be propagated because it gets caught", to have the same form as the examples below ("This exception is propagated by...").

File: kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt [hunk 10]
```diff
@@ -40,70 +40,257 @@ internal fun handlerException(originalException: Throwable, thrownException: Thr
...
+ *     """)
+ * }
+ * ```
+ *
+ * An exception is considered to be propagated if it's transferred to the parent
+ * through [structured concurrency][CoroutineScope]:
+ *
+ * ```
+ * coroutineScope {
+ *     launch {
```
Comment (murfel) [inline kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt:137]: Consider something like `scope.launch { ... }`, so that it's not lexically scoped and does not interfere with the previous example.

Comment (murfel) [reply kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt:137]: Although I see that it's a bit tricky that it requires asserting that the `scope` must have a CEH installed.

Comment (murfel) [reply kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt:137]: Then maybe introduce the caller for the line 124, something like a function where `coroutineScope` is called.

File: kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt [hunk 11]
```diff
@@ -40,70 +40,257 @@ internal fun handlerException(originalException: Throwable, thrownException: Thr
...
+ * // This function will throw an `IllegalStateException`
+ * coroutineScope {
+ *     throw IllegalStateException("""
+ *         This exception is propagated
+ *         by being rethrown to the caller.
+ *     """)
+ * }
+ * ```
+ *
+ * An exception is considered to be propagated if it's transferred to the parent
```
Comment (murfel) [inline kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt:132]: Simplify and use a single form for all "propagated" mentions in all three examples, or at least this one and the next one: "an exception is propagated if ..."

File: kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt [hunk 12]
```diff
@@ -40,70 +40,257 @@ internal fun handlerException(originalException: Throwable, thrownException: Thr
...
+ *     throw IllegalStateException("""
+ *         This exception is propagated,
+ *         since calling `await()` on `deferred`
+ *         will rethrow the exception.
+ *     """)
+ * }
+ * ```
  *
- * ### Handling coroutine exceptions
+ * When none of the propagation paths listed above apply, an exception can not be propagated.
```
Comment (murfel) [inline kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt]: "cannot"

File: kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt [hunk 13]
```diff
@@ -40,70 +40,257 @@ internal fun handlerException(originalException: Throwable, thrownException: Thr
...
  *
- * `CoroutineExceptionHandler` is a last-resort mechanism for global "catch all" behavior.
- * You cannot recover from the exception in the `CoroutineExceptionHandler`. The coroutine had already completed
- * with the corresponding exception when the handler is called. Normally, the handler is used to
- * log the exception, show some kind of error message, terminate, and/or restart the application.
+ * ```
+ * supervisorScope {
+ *     launch {
+ *         throw IllegalStateException("""
+ *             This *is* an exception with no propagation path, since
```
Comment (murfel) [inline kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt]: The stressed "is" was unexpected, it is unclear what it is contrasted with (there was no "is not" to contrast it with). I'd stress the **no propagation path** bit. To be consistent with previous examples, the text could be "This exception has **no propagation path**".

File: kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt [hunk 14]
```diff
@@ -40,70 +40,257 @@ internal fun handlerException(originalException: Throwable, thrownException: Thr
...
+ * ### Platform-specific last-resort handling of lost exceptions
+ *
+ * When no [CoroutineExceptionHandler] is present in the [CoroutineContext] of the failing coroutine,
+ * an exception with no propagation path is handled in the following way as the last-resort measure:
+ *
+ * - On JVM, all instances of [CoroutineExceptionHandler] found via `ServiceLoader` and
+ *   the current thread's `Thread.uncaughtExceptionHandler` are invoked.
+ * - On Native, the whole application crashes with the exception.
+ * - On JS and Wasm JS, the exception is propagated into the JavaScript runtime's event loop
+ *   and is processed in a platform-specific way determined by the platform itself.
```
Comment (murfel) [inline kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt]: We can now say that on web, `reportError` is property-tested and invoked, if exists. Otherwise it is rethrown.

File: kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt [hunk 15]
```diff
@@ -40,70 +40,257 @@ internal fun handlerException(originalException: Throwable, thrownException: Thr
...
+ *
```
Comment (murfel) [inline kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt]: Is Wasm/Wasi omission intentional?

File: kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt [hunk 16]
```diff
@@ -40,70 +40,257 @@ internal fun handlerException(originalException: Throwable, thrownException: Thr
...
+ *         error("Error")
+ *     }
+ * }
+ * ```
+ *
+ * It will print `Outer`, even though the coroutine where the failure originally happened specifies its own
+ * [CoroutineExceptionHandler].
+ * The explanation is that initially, the exception *does* have a propagation path and will get propagated to the
+ * parent coroutine using structured concurrency.
+ * The parent itself, however, has no viable propagation path and has to use *its* [CoroutineExceptionHandler].
```
Comment (murfel) [inline kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt]: **its own**

File: kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt [hunk 17]
```diff
@@ -40,70 +40,257 @@ internal fun handlerException(originalException: Throwable, thrownException: Thr
...
+ *
+ * Similarly, this [CoroutineExceptionHandler] is redundant and will never be invoked:
+ *
+ * ```
+ * GlobalScope.async(CoroutineExceptionHandler { ctx, e -> println("Failure") }) {
```
Comment (murfel) [inline kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt]: Failure -> Won't ever be invoke, to be consistent with other examples

File: kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt [hunk 18]
```diff
@@ -40,70 +40,257 @@ internal fun handlerException(originalException: Throwable, thrownException: Thr
...
     /**
-     * Key for [CoroutineExceptionHandler] instance in the coroutine context.
+     * Key for the [CoroutineExceptionHandler] instance in a coroutine context.
      */
     public companion object Key : CoroutineContext.Key<CoroutineExceptionHandler>
 
     /**
-     * Handles uncaught [exception] in the given [context]. It is invoked
-     * if the coroutine has an uncaught exception.
+     * Handles an [exception] in the given [context].
```
Comment (murfel) [inline kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt]: "**in** the given context" can be misinterpreted as if the handler is called from within the provided context.

File: kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt [hunk 19]
```diff
@@ -40,70 +40,257 @@ internal fun handlerException(originalException: Throwable, thrownException: Thr
...
+ * coroutineScope {
+ *     launch(CoroutineExceptionHandler { ctx, ex ->
+ *         println("This line will not be printed!")
+ *     }) {
+ *         error("This failure will cancel `coroutineScope`!")
+ *     }
+ * }
+ * ```
+ *
+ * A [CoroutineExceptionHandler] has no effect in this scenario: the failure in [launch] will cancel [coroutineScope].
```
Comment (murfel) [inline kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt]: Spell out the rules according to which this example works:
> `launch` has a propagation path, so the error is propagated to the parent, and the CEH will never be invoked

File: kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt [hunk 20]
```diff
@@ -40,70 +40,257 @@ internal fun handlerException(originalException: Throwable, thrownException: Thr
...
+ * Using `try`/`catch` is the proper way to achieve this.
```
Comment (murfel) [inline kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt]: Spell out "this" to avoid accidentally referring to the previous sentence and specify where the try-catch should go (there are two options: inside and outside launch).

> To avoid the parent coroutine from being cancelled from a launch exception, wrap the call to launch into a try-catch (and also possibly reconsider your design?)

File: kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt [hunk 21]
```diff
@@ -40,70 +40,257 @@ internal fun handlerException(originalException: Throwable, thrownException: Thr
...
  * ```
  *
- * ### Uncaught exceptions with no handler
+ * Alternatively, whenever a failure is indeed supposed to terminate a coroutine,
+ * using [async] instead of [launch] and later calling [Deferred.await] instead of [Job.join]
+ * on its result to check if the computation was successful will allow gracefully processing the exception.
+ *
+ * ### Pitfalls
+ *
+ * #### Using a [CoroutineExceptionHandler] does not prevent coroutine failures
```
Comment (murfel) [inline kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt:227]: Something is confusing me in this example, but I can't quite pinpoint it. I'll take a look at it again after the next set of changes.

Comment (murfel) [reply kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt:227]: Possibly, it's that there are a few mistakes/misconceptions combined together.
* A CEH doesn't prevent a coroutine from failing.
* A CEH is not called if there exists a propagation path.
* And possibly something else?

**Comment by murfel** [comment]
This version reads much lighter and less technical, although I am already tainted and cannot make a fair judgement.

File: kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt (hunk 15 above)
Comment (dkhalanskyjb) [reply kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt]: Nope, good catch!

File: kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt (hunk 21 above)
Comment (dkhalanskyjb) [reply kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt:227]: Your analysis is spot-on. Indeed, to make a mistake shown in this section, you need to be completely unaware of what coroutine exception handlers do. We can expect people to be that unaware, though! Context: https://github.com/Kotlin/kotlinx.coroutines/pull/1886#discussion_r400394293
Also, believing `CoroutineExceptionHandler` behaves as `catch` does isn't even unreasonable. In languages with effect handlers, you can redefine the behavior of `throw`. Even absent that, it's quite natural to believe an exception handler will at least prevent a coroutine from cancelling its parent: after all, the exception was "handled".

File: kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt (hunk 10 above)
Comment (dkhalanskyjb) [reply kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt:137]: > it requires asserting that the scope must have a CEH installed.

This particular example requires asserting that the parent job is a normal one and not a `SupervisorJob`. Manually constructing such a scope would detract from the example and highlights `CoroutineScope()`, whose usage we want to discourage. In any case, it's unclear to me what issue you're describing. The example is the simplest one that illustrates children propagating exceptions to their parents.

File: kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt (hunk 11 above)
Comment (dkhalanskyjb) [reply kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt:132]: I don't see the value in it, and there are slight semantic differences between the three cases.
* In the first scenario, rethrowing is *the* direct act of propagation.
* In the second scenario, being transferred is like a checkmark on the propagation sheet: it may not be the only one, or even the most important act of propagation, but it suffices.
* In the third scenario, the exception isn't meaningfully propagated in the program-logic sense. Instead, `kotlinx.coroutines` considers its propagation job done if the exception can in theory be queried afterwards somehow.
