### PR TITLE
Re-structure DebugProbes documentation and mention classloading

### LINKED ISSUE #4000: `kotlinx.coroutines.debug`'s `DebugProbes` fails when used from a different ClassLoader as `kotlin.stdlib`
**Describe the bug**

`DebugProbes.install()` works, but the code crashed when spawning the first coroutine after installation, with `java.lang.ClassNotFoundException: kotlinx.coroutines.debug.internal.DebugProbesImpl`.

First, a quick context on our different module layers hierarchy (we use JPMS), our module layers are structured like such:
```
Layer "fleet.dock.bootstrap" (`AppClassLoader`)
    -> Module `fleet.dock.bootstrap`
    -> Module `kotlin.stdlib`
    -> [...]
  └── Layer "fleet.dock.api"
      -> Module `fleet.dock.api`
      -> Module `kotlinx.coroutines.core`
      -> Module `kotlinx.coroutines.debug`
      -> [...]
```
_Note: Module layers does not have names, I just name them by the most significant module that is part of it for convenience._

Here is what I think is happening, internally, when doing `DebugProbes.install()`, `kotlinx.coroutines.debug` uses ByteBuddy to [swap](https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-debug/src/internal/Attach.kt#L20-L30) `kotlin.stdlib`'s `kotlin.coroutines.jvm.internal.DebugProbesKt` code with the [code from `kotlinx.coroutines.core`'s `kotlinx.coroutines.debug.internal.DebugProbesKt`](https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-core/jvm/src/debug/internal/DebugProbes.kt).
This runtime injected code tries to use [`DebugProbesImpl` object](https://github.com/Kotlin/kotlinx.coroutines/blob/39ea109008e7de1233f7b650fd88980f037b5c1b/kotlinx-coroutines-core/jvm/src/debug/internal/DebugProbes.kt#L18C62-L18C77) from `kotlinx.coroutines.core` module. But it does that at the `kotlin.stdlib` level, so using the `fleet.dock.bootstrap`'s ClassLoader (`AppClassLoader`), which does not know about `kotlinx.coroutines.core` module and so it crashes with `ClassNotFoundException`.

### PR DESCRIPTION
**Pull request by qwwdfsad**
Fixes #4000

### CODE REVIEW

File: kotlinx-coroutines-debug/src/DebugProbes.kt [hunk 1]
```diff
@@ -24,16 +25,26 @@ import kotlin.coroutines.*
...
- * * `probeCoroutineSuspended` is invoked on every continuation suspension.
- * * `probeCoroutineCreated` is invoked on every coroutine creation.
- *
  * ### Overhead
- *  * Every created coroutine is stored in a concurrent hash map and hash map is looked up and
+ *
+ *  - Every created coroutine is stored in a concurrent hash map and hash map is looked up and
  *    updated on each suspension and resumption.
- *  * If [DebugProbes.enableCreationStackTraces] is enabled, stack trace of the current thread is captured on
+ *  - If [DebugProbes.enableCreationStackTraces] is enabled, stack trace of the current thread is captured on
```
Comment (qwwdfsad) [inline kotlinx-coroutines-debug/src/DebugProbes.kt:32]: While we mention' KDoc' from time to time, I'd like to hear your opinion here.

WDYT about making dashes the recommended (notably: KDoc spec, our libraries, IDEAs autoformatter and quickfixes) way for unordered lists instead of asterisks? I find it slightly more approachable than multiple asterisks (because of the one required by KDoc itself) especially when multiple levels of nesting are involved

File: kotlinx-coroutines-debug/src/DebugProbes.kt [hunk 2]
```diff
@@ -9,11 +9,12 @@ import java.lang.management.*
...
 
 /**
- * Debug probes support.
+ * Kotlin debug probes support.
  *
  * Debug probes is a dynamic attach mechanism which installs multiple hooks into coroutines machinery.
- * It slows down all coroutine-related code, but in return provides a lot of diagnostic information, including
- * asynchronous stack-traces and coroutine dumps (similar to [ThreadMXBean.dumpAllThreads] and `jstack` via [DebugProbes.dumpCoroutines].
+ * It slows down all coroutine-related code, but in return provides diagnostic information, including
+ * asynchronous stacktraces, coroutine dumps (similar to [ThreadMXBean.dumpAllThreads] and `jstack` via [DebugProbes.dumpCoroutines]
```
Comment (dkhalanskyjb) [inline kotlinx-coroutines-debug/src/DebugProbes.kt:16]:
```suggestion
 * asynchronous stacktraces, coroutine dumps (similar to [ThreadMXBean.dumpAllThreads] and `jstack`) via [DebugProbes.dumpCoroutines],
```

File: kotlinx-coroutines-debug/src/DebugProbes.kt [hunk 3]
```diff
@@ -24,16 +25,26 @@ import kotlin.coroutines.*
...
  *
- * ### Installed hooks
- * * `probeCoroutineResumed` is invoked on every [Continuation.resume].
- * * `probeCoroutineSuspended` is invoked on every continuation suspension.
- * * `probeCoroutineCreated` is invoked on every coroutine creation.
- *
  * ### Overhead
- *  * Every created coroutine is stored in a concurrent hash map and hash map is looked up and
+ *
+ *  - Every created coroutine is stored in a concurrent hash map and hash map is looked up and
```
Comment (dkhalanskyjb) [inline kotlinx-coroutines-debug/src/DebugProbes.kt:30]:
```suggestion
 *  - Every created coroutine is stored in a concurrent hash map, and the hash map is looked up in and
```

File: kotlinx-coroutines-debug/src/DebugProbes.kt [hunk 4]
```diff
@@ -24,16 +25,26 @@ import kotlin.coroutines.*
...
  *    updated on each suspension and resumption.
- *  * If [DebugProbes.enableCreationStackTraces] is enabled, stack trace of the current thread is captured on
+ *  - If [DebugProbes.enableCreationStackTraces] is enabled, stack trace of the current thread is captured on
  *    each created coroutine that is a rough equivalent of throwing an exception per each created coroutine.
+ *
+ * ### Internal machinery and classloading.
+ *
+ * Under the hood, debug probes replace internal `kotlin.coroutines.jvm.internal.DebugProbesKt` class with the following
+ * empty static methods:
```
Comment (dkhalanskyjb) [inline kotlinx-coroutines-debug/src/DebugProbes.kt:38]:
```suggestion
 * Under the hood, debug probes replace internal `kotlin.coroutines.jvm.internal.DebugProbesKt` class that has the following
 * empty static methods:
```

Otherwise, we get the somewhat confusing "replace A with B with C."

File: kotlinx-coroutines-debug/src/DebugProbes.kt [hunk 5]
```diff
@@ -24,16 +25,26 @@ import kotlin.coroutines.*
...
+ *
+ * - `probeCoroutineResumed` that is invoked on every [Continuation.resume].
+ * - `probeCoroutineSuspended` that is invoked on every continuation suspension.
+ * - `probeCoroutineCreated` that is invoked on every coroutine creation.
+ *
+ * with `kotlinx-coroutines`-specific class to keep track of all the coroutines machinery.
```
Comment (dkhalanskyjb) [inline kotlinx-coroutines-debug/src/DebugProbes.kt:44]:
```suggestion
 * with a `kotlinx-coroutines`-specific class to keep track of all the coroutines machinery.
```

File: kotlinx-coroutines-debug/src/DebugProbes.kt [hunk 6]
```diff
@@ -24,16 +25,26 @@ import kotlin.coroutines.*
...
+ *
+ * The new class is located in `kotlinx-coroutines-core` module meaning that all target application classes that use
```
Comment (dkhalanskyjb) [inline kotlinx-coroutines-debug/src/DebugProbes.kt:46]:
```suggestion
 * The new class is located in the `kotlinx-coroutines-core` module, meaning that all target application classes that use
```

File: kotlinx-coroutines-debug/src/DebugProbes.kt [hunk 7]
```diff
@@ -24,16 +25,26 @@ import kotlin.coroutines.*
...
+ * coroutines and `suspend` functions have to be loaded by the classloader for which `kotlinx-coroutines-core` classes are avilable.
```
Comment (dkhalanskyjb) [inline kotlinx-coroutines-debug/src/DebugProbes.kt:47]:
```suggestion
 * coroutines and `suspend` functions have to be loaded by the classloader in which `kotlinx-coroutines-core` classes are available.
```

File: kotlinx-coroutines-debug/src/DebugProbes.kt (hunk 1 above)
Comment (dkhalanskyjb) [reply kotlinx-coroutines-debug/src/DebugProbes.kt:32]: Sure: https://github.com/Kotlin/kotlinx.coroutines/pull/4027

Comment (qwwdfsad) [reply kotlinx-coroutines-debug/src/DebugProbes.kt:32]: Filed https://youtrack.jetbrains.com/issue/KTIJ-28654/KDoc-autoformatting-replace-asterisks-with-dashes-for-list-declaration

**Review by dkhalanskyjb — APPROVED** [review]
