### PR TITLE
Dispose waiting node when Deferred.await is cancelled

### LINKED ISSUE #893: Exception inside async {} is logged by uncaught exception handler
I can't find anything in the docs to explain why the following is or isn't a bug:

```kotlin
fun main(args: Array<String>) {
    val job = SupervisorJob()
    val scope = CoroutineScope(job + Dispatchers.Default)

    val deferred = GlobalScope.async(Dispatchers.Default, start = CoroutineStart.LAZY) {
        delay(5000)
        throw Exception("boom")
    }

    scope.launch {
        try {
            deferred.await()
        } catch (e: Exception) {
            println("error awaiting: $e")
        }
    }

    runBlocking {
        job.cancelAndJoin()

        try {
            deferred.await()
        } catch (e: Exception) {
            println("2nd await() caught $e")
        }
    }


    Thread.sleep(10000)
}
```

Results in:
```
error awaiting: kotlinx.coroutines.JobCancellationException: Job was cancelled; job=SupervisorJobImpl{Cancelling}@57ead6a
.
. (5 seconds later)
.
Exception in thread "DefaultDispatcher-worker-1" java.lang.Exception: boom
	at com.inductiveautomation.ignition.gateway.opcua.AsyncKt$main$deferred$1.invokeSuspend(async.kt:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	at kotlinx.coroutines.DispatchedTask$DefaultImpls.run(Dispatched.kt:235)
	at kotlinx.coroutines.AbstractContinuation.run(AbstractContinuation.kt:19)
	at kotlinx.coroutines.scheduling.Task.run(Tasks.kt:94)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:586)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:732)
2nd await() caught java.lang.Exception: boom
```

The uncaught exception handler prints the exception after the 5 second delay expires whether or not the second call to `await()` is made.

Without the cancellation it behaves as expected:
```
error awaiting: java.lang.Exception: boom
2nd await() caught java.lang.Exception: boom
```

### PR DESCRIPTION
**Pull request by elizarov**
This is part of the problem that is shown in issue #893. The other
part of the problem (what happens during race) is addressed by PR #896

Fixes #893

### CODE REVIEW

File: core/kotlinx-coroutines-core/test/CancelledAwaitStressTest.kt [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+    @Test
+    fun testCancelledAwait() = runTest {
+        val d = async {
+            delay(Long.MAX_VALUE)
+        }
+        repeat(n) {
+            val waiter = launch(start = CoroutineStart.UNDISPATCHED) {
+                val a = ByteArray(10000000) // allocate 10M of memory here
+                d.await()
+                println(a) // make sure it is kept in state machine
```
Comment (qwwdfsad) [inline core/kotlinx-coroutines-core/test/CancelledAwaitStressTest.kt]: please do not use `println` in tests
