### PR TITLE
Cancel current Job on RejectedExecutionException

### LINKED ISSUE #2003: Coroutines launch on default dispatcher when they should not
In one of our production services we had a fixed thread-pool for handling blocking DB calls, and we are using `withContext` and `asCoroutineDispatcher` to launch such calls in context of DB threads. These calls have to stick to these thread-pool we have created otherwise they fail:
```kotlin
          val executor = ThreadPoolExecutor(
                affinity,
                MAX_IO_THREADS,
                DEFAULT_TTL_SECONDS_THREAD,
                TimeUnit.SECONDS,
                SynchronousQueue()
            ) { runnable ->
                Thread(runnable).also {
                    it.name = "io-pool-${it.id}"
                    it.isDaemon = true
                    it.priority = Thread.NORM_PRIORITY
                }
            }
          
          val dispatcher = executor.asCoroutineDispatcher()
```

**Notice** `SynchronousQueue` to block spinning off any further threads/calls in when pool is full. Turns out looking at code of `ExecutorCoroutineDispatcherBase` https://github.com/Kotlin/kotlinx.coroutines/blob/d7de5f5ba66a8d005e5cbd03b18522112303fd54/kotlinx-coroutines-core/jvm/src/Executors.kt#L80-L87 turns out we launch/enqueue or coroutine on `DefaultExecutor`. This has multiple problems:

 - It breaks the foundational assumption of respecting dispatcher that was supplied, worst part of this is that it's undocumented caveat. 
 - It can result in a flurry of undesired threads; ultimately leading to OOM with it's existing behavior. Having an unbound queue or unbound set of threads is exactly what should be avoided at all costs.

Here is a simple [example to reproduce this issue locally](https://pl.kotl.in/3iPiVQjir):
```kotlin
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.asCoroutineDispatcher
import kotlinx.coroutines.async
import kotlinx.coroutines.awaitAll
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import kotlinx.coroutines.withContext
import java.util.concurrent.Executors
import java.util.concurrent.SynchronousQueue
import java.util.concurrent.ThreadPoolExecutor
import java.util.concurrent.TimeUnit

val executor = ThreadPoolExecutor(1, 1, 60, TimeUnit.SECONDS, SynchronousQueue()) { runnable ->
    Thread(runnable).also {
        it.name = "io-pool-${it.id}"
        it.isDaemon = true
        it.priority = Thread.NORM_PRIORITY
    }
}

fun main() {
    runBlocking(executor.asCoroutineDispatcher()) {
        for (i in 1..5) {
            launch {
                println(Thread.currentThread().name)
                Thread.sleep(1000)
            }
        }
    }
}
```

I believe the subsequent co-routines should be rejected; launching by default on `DefaultExecutor` is an undesired behavior and breaks fundamental assumption.

### PR DESCRIPTION
**Pull request by elizarov**
When the Executor that was used with Executor.asCoroutineDispatcher() extension rejects submitted task, it means that it had reached its capacity and so the executing current Job should be cancelled to terminate it as soon as possible. This way RejectedExecutionException works as a rate-limiter just like it serves this purpose in executor-based Java code.

**NOTE**: This PR changes internal coroutines API for `Delay` interface which some 3rd part code might be using, so it should be merged only in the major release.

Fixes #2003

### CODE REVIEW

File: kotlinx-coroutines-core/jvm/src/Executors.kt [hunk 1]
```diff
@@ -38,13 +38,23 @@ public abstract class ExecutorCoroutineDispatcher: CoroutineDispatcher(), Closea
 
 /**
  * Converts an instance of [ExecutorService] to an implementation of [ExecutorCoroutineDispatcher].
+ *
+ * Note, that if the underlying executor uses limited queues and throws [RejectedExecutionException] on
```
Comment (fvasco) [inline kotlinx-coroutines-core/jvm/src/Executors.kt:42]: Job is cancelled iff the executor refects a task, indipendently if is queue is limited or not (ie on shutdown). Same in `Executor.asCoroutineDispatcher()`.

File: kotlinx-coroutines-core/jvm/src/Executors.kt [hunk 2]
```diff
@@ -38,13 +38,23 @@ public abstract class ExecutorCoroutineDispatcher: CoroutineDispatcher(), Closea
...
+ * attempt to submit a task, then the [Job] of the affected task is [cancelled][Job.cancel] and the
```
Comment (fvasco) [inline kotlinx-coroutines-core/jvm/src/Executors.kt:43]: I don't know if this is the right point to explain that a cancellation can happen at coroutine start, cancellation and in any suspension point.

File: kotlinx-coroutines-core/jvm/src/Executors.kt (hunk 1 above)
Comment (elizarov) [reply kotlinx-coroutines-core/jvm/src/Executors.kt]: I've clarified docs a bit. Check it out.

File: kotlinx-coroutines-core/jvm/src/Executors.kt (hunk 2 above)
Comment (elizarov) [reply kotlinx-coroutines-core/jvm/src/Executors.kt]: That's probably going too much into the details and basics that are explained elsewhere.

File: kotlinx-coroutines-core/jvm/src/Executors.kt (hunk 1 above)
Comment (fvasco) [reply kotlinx-coroutines-core/jvm/src/Executors.kt]: Looks good to me.

File: kotlinx-coroutines-core/jvm/src/Executors.kt [hunk 3]
```diff
@@ -38,13 +38,23 @@ public abstract class ExecutorCoroutineDispatcher: CoroutineDispatcher(), Closea
...
+ * [Dispatchers.IO], so that the affected coroutine can cleanup its resources and promptly complete.
  */
 @JvmName("from") // this is for a nice Java API, see issue #255
 public fun ExecutorService.asCoroutineDispatcher(): ExecutorCoroutineDispatcher =
     ExecutorCoroutineDispatcherImpl(this)
 
 /**
  * Converts an instance of [Executor] to an implementation of [CoroutineDispatcher].
+ *
+ * Note, that if the underlying executor throws [RejectedExecutionException] on
```
Comment (qwwdfsad) [inline kotlinx-coroutines-core/jvm/src/Executors.kt:54]: The same comment worth adding to `newSingleThreadContext` and `newFixedThreadPoolContext`

Comment (fvasco) [reply kotlinx-coroutines-core/jvm/src/Executors.kt:54]: ...and tests to avoid regression.

**Comment by elizarov** [comment]
I've made better tests and docs. 

NOTE: It should be merged on the next major update (`1.4.0`) only, because it updates `Delay` interface APIs. Even though it is an `@InternalCoroutinesApi`, still extra caution will not harm.

**Review by qwwdfsad — APPROVED** [review]

**Review by qwwdfsad — APPROVED** [review]
